### ISSUE TITLE
Invoked tasks don't pick up ENV variables

### ISSUE THREAD

**Issue by razielgn** [mina-deploy/mina#11]
I have the following .bash_profile on the server:

```
export MONGODB_URI="mongodb://localhost/db"
```

However when assets get precompiled an thus the Rails app gets loaded I get

```
rake aborted!
db_name must be a string or symbol

Tasks: TOP => environment
(See full trace by running task with --trace)
rake aborted!
```

Meaning mongodb's ENV variable isn't picked up.
When I force mina to invoke `source ~/.bash_profile && rake assets:precompile` everything goes right.

**Comment by matheusvetor** [comment]
I was trying to deploy but my server is behind a proxy. I used the @razielgn hook to set env http_proxy variable and it worked. Thanks!

```
task :env do
  queue %{
    echo "-----> Seting environment variables"
    #{echo_cmd %[export http_proxy=http://proxy-ip:port]}
    #{echo_cmd %[export https_proxy=http://proxy-ip:port]}
  }
end

desc "Deploys the current version to the server."
task :deploy => :environment do
  invoke :env

  deploy do
    invoke :'sidekiq:quiet'
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'
    invoke :'bundle:install'
    invoke :'rails:db_migrate'
    invoke :'rails:assets_precompile'

    to :launch do
      # invoke :'sidekiq:restart'
      queue "touch #{deploy_to}/shared/tmp/restart.txt"
    end
  end
end
```

**Comment by diegocastro** [comment]
Thanks @matheusvetor it saved my symfony deploy. There should be an easier way to do this.

**Comment by bbnnt** [comment]
:+1:  :100: 
Got into this problem using sidekiq, it was not picking up the environment variables.
Saved me a lot of time
