### ISSUE TITLE
When config.assets.prefix was setting, the assets was precompiled every deploy

### ISSUE THREAD

**Issue by huobazi** [mina-deploy/mina#125]
When i setting config.assets.prefix in my rails application 
such as 
```ruby
    config.assets.prefix = "/rs/2013"
```
The assets was compile every times by deploy
I found some hardcode in https://github.com/nadarei/mina/blob/master/lib/mina/rails.rb#L189

Then i want to try fix it 
https://github.com/huobazi/mina/blob/assets-check-with_assets_prefx/lib/mina/rails.rb#L188

Unfortunatly, It was not works for me. it was also compile assets every deploy.

**Comment by d4be4st** [comment]
this will be fixed in new release with 

`set_default :compiled_asset_path, 'public/assets'`
