### ISSUE TITLE
rvm is sourced, which just prints the help message

### ISSUE THREAD

**Issue by brightbits** [mina-deploy/mina#131]
I'm using system-wide rvm at /usr/local/rvm/bin/rvm.

The rvm.rb @ lib/mina/rvm.rb

calls source #{rvm_path}

which every time I deploy prints the rvm usage (or whatever is printed when you run rvm in the terminal)

Everything works though, its just a bit annoying.. Any ideas?

**Comment by d4be4st** [comment]
this is rvm errors, do not know how to avoid. Sorry
