### ISSUE TITLE
`mina deploy` hangs

### ISSUE THREAD

**Issue by 7even** [mina-deploy/mina#134]
The deployment process hangs from time to time. Usually it happens at the very end, after outputting `Done. Deployed v6` but sometimes it hangs after some error occured in the middle of the process.

Subsequent `Ctrl+C` don't help, I just keep getting `Mina: SIGINT received again. Force quitting...` over and over again; I have to `kill -9` the process.

This reproduces on 2 different machines, both of them use [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh), [rbenv](https://github.com/sstephenson/rbenv) and ruby version 1.9.2 or greater. I would gladly provide a more reproducible environment if I could.

**Comment by Cofyc** [comment]
+1 This problem bothers me...

**Comment by Cofyc** [comment]
@scarfacedeb Found a way to disable `ControlPersist` in `mina`. Add

```
set :ssh_options, '-oControlPersist=no
````

in your `config/deploy.rb`.
