### ISSUE TITLE
Enable wiki to list plugins/gems

### ISSUE THREAD

**Issue by moll** [mina-deploy/mina#140]
Hello!

I created [Mina::Rsync](https://github.com/moll/mina-rsync) to easily deploy apps with Rsync. I propose to enable the wiki here on GitHub so we could list related plugins and gems.

**Comment by d4be4st** [comment]
you can edit https://github.com/mina-deploy/mina/blob/master/support/third_party_modules.md and make a PR

**Comment by moll** [comment]
Thanks. I see it's already there. :-)
