### ISSUE TITLE
Changes of assets under lib/assets does not trigger assets_precompile 

### ISSUE THREAD

**Issue by xhh** [mina-deploy/mina#143]
When js/css files under *lib/assets/javascripts* and *lib/assets/stylesheets* are changed, mina skips the asset precompilation, which should be incorrect, right?

**Comment by d4be4st** [comment]
default assest path do not include lib
`set_default :asset_paths, ['vendor/assets/', 'app/assets/']`

you can override it in deploy.rb to include lib

`set :asset_paths, ['vendor/assets/', 'app/assets/', 'lib/assets']`
