### ISSUE TITLE
Trust foreman binary

### ISSUE THREAD

**Issue by jrhorn424** [mina-deploy/mina#144]
With the proliferation of binstubs and the new practice of checking gem binaries into `app/bin`, the foreman module should trust the correct foreman binary is being executed. 

The problem is [here](https://github.com/nadarei/mina/blob/e655330bcc84264e3f337be9e199f730a4473250/lib/mina/foreman.rb#L47).

I run `bundle install` without sudo since I have permissions setup correctly, and a proper gem setup that I can write to. `sudo`'ing bypasses my `chruby`, and the short of it is `bundle` is nowhere to be found for the `sudo`er.

One fix would be to not require `sudo` for this line. Another would be to not require `sudo` or `bundle exec`. I'd like to get feedback before working on a patch.

**Comment by d4be4st** [comment]
Is this bug still happening?

**Comment by jrhorn424** [comment]
I can no longer reproduce this. I don't have this project any longer, and I don't deploy regularly anymore.
