### ISSUE TITLE
Broken JRuby support

### ISSUE THREAD

**Issue by mrbrdo** [mina-deploy/mina#147]
At some point in time you broke JRuby support by using fork (unsupported) in https://github.com/nadarei/mina/blob/master/lib/mina/exec_helpers.rb

You could perhaps use threads for this purpose and `rescue Interrupt` instead of `trap('INT')`.

**Comment by d4be4st** [comment]
I really do not know if this is fixed. If someone tried using newer mina version with JRuby and doesnt work please repoen the task

**Comment by xurde** [comment]
Hi @mrbrdo 
So did this finally got solved and properly patched for the following versions?
The status looks uncertain.
Thanks!

**Comment by mrbrdo** [comment]
Yes since the patch is merged I think it should work now.

**Comment by ineu** [comment]
Sorry to raise the old issue, but this seems to be broken again as of 1.0.6. Trying to run it under jruby 9, I get the following error:
```
> $ mina deploy
mina aborted!
NotImplementedError: fork is not available on this platform
```

**Comment by zhum** [comment]
The same problem! Please, fix for jruby...

**Comment by vicvans20** [comment]
Same problem with jruby 9.1.7.0

**Comment by prasadsurase** [comment]
Same problem with jruby 9.1.15.0

**Comment by zhum** [comment]
Please, accept my patch... https://github.com/mina-deploy/mina/pull/581/
I use it in production, my patched mina works fine with jruby.
