### ISSUE TITLE
in_directory uses new @to

### ISSUE THREAD

**Issue by lasseebert** [mina-deploy/mina#149]
When using the `in_directory` helper it replaces the current `@to` with `:default`. This is a big gotcha when doing stuff like:

    to :launch do
      in_directory release_path do
        # Will not be added to :launch, but to :default
        invoke :start_something
      end
    end

Is this the wanted behavior or is it a bug?

**Comment by d4be4st** [comment]
to and in_directory are not meant to be used nested.
You will need to create a separate task which uses in_directory. sorry
