### ISSUE TITLE
Add support for ssh proxies

### ISSUE THREAD

**Issue by allanwind** [mina-deploy/mina#151]
capistrano can deploys to hosts behind a ssh gateway server via the :gateway setting.  We use the this little piece of magic to transparently deploy in or outside the office:

```
unless `hostname -f` =~ /#{intranet}$/
        hosts_via_gateway = find_servers.map { |sd| sd.to_s }.select { |h| h =~ /#{intranet}$/ }
        unless hosts_via_gateway.empty?
                set :gateway, '#{gateway}' => hosts_via_gateway
        end
end
```

**Comment by d4be4st** [comment]
You can make a gem for this that will extend mina to support gateways.
