### ISSUE TITLE
How to select project folder under git control

### ISSUE THREAD

**Issue by fanweixiao** [mina-deploy/mina#155]
e.g. my git repo may looks like:

git.repo/a/b/proj1
git.repo/a/b/proj2
git.repo/a/b/proj3

When i only want to deploy proj1, how can I only copy contents of /a/b/proj1 ot deploy_to ?

**Comment by pruett** [comment]
I am curious about this question as well. Do you recommend running a task after deployment that will manually `rm -rf` unwanted files/folders?

**Comment by fanweixiao** [comment]
@pruett mina first get scm files, then copy whole folder to Release dir, actually we can only copy indicate one to Release to complete this.

**Comment by d4be4st** [comment]
Mina works on assumptions that the repository contains only one app. 
You can always make a task which will symlink the correct folder within releases path to /current but whole repo will be feched every time
