### ISSUE TITLE
mina setup freezes at password

### ISSUE THREAD

**Issue by martinskruze** [mina-deploy/mina#163]
Hi!

I have a bit of issue here - description below:
deploy.rb is more or less unchanged from standard - filled everything in (domain, deploy_to, repository and branch) (just added extra user and port (set :user, "my_user_name", set :port, "my_port_number"))

after i execute - mina setup -t -v

```
** Invoke setup (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute setup
my_user_name@my_domain's password: 
```

It kinda don't accepts password - when i enter password and press "Enter" - the cursor still continuous to blink at same spot

nothing happens and after Ctrl+C:

```
-----> Mina: SIGINT received.
       Elapsed time: 99.00 seconds
```

Versions: Ruby 2.0.0, Rails 4.0.2

That is it!
ANY IDEAS?

**Comment by xiaocuixt** [comment]
try like this: http://stackoverflow.com/questions/22606771/nothing-happens-when-doing-mina-setup
