### ISSUE TITLE
AWS EC2 .pem file

### ISSUE THREAD

**Issue by basmoura** [mina-deploy/mina#164]
Hi, i want deploy with mina to my aws ec2 instance, but i need use the amazon's .pem file to have ssh access. Does mina support this? If so, how can i do it?

**Comment by hangkimduyen** [comment]
how did you add id_rsa.pub key in the authorized_keys at ubuntu?

**Comment by grsahil20** [comment]
any updates on how can we use .pem to ssh with mina ?

**Comment by CT-Kamlesh** [comment]
Not able to deploy to EC2 instance with mina.
Hoping for updates

**Comment by digaoddc** [comment]
If someone has the same problem, do these steps:

1) Connect to your instance using the pem file: `ssh user@x.x.x.x -i ~/some-path/file.pem`
2) Create a new SSH key in your local machine
3) Copy the Public key from your local machine the path `~/.ssh/authorized_keys` in the server.
