### ISSUE TITLE
Deployment with Github WebHook URLs..

### ISSUE THREAD

**Issue by zaidakram** [mina-deploy/mina#165]
Im trying to automate the process of deployment. Like if code is pushed on master branch it gets deployed immediately via WebHook (Post Recieve). Problem is WebHook URL is also  of the same app. 
So I need to run Mina task in a controller (Rails app) Without SSH to the box, Which in turn is to the sam box. (deployment on the same machine).

Any Kind of help is appreciated...

**Comment by abitrolly** [comment]
@zaidakram how did you solve the issue?
