### ISSUE TITLE
Inaccurate documentation copy?

### ISSUE THREAD

**Issue by leehambley** [mina-deploy/mina#167]
> Compare this to the likes of Vlad or Capistrano, where each command is ran separately on their own SSH sessions. Mina only creates one SSH session per deploy, minimizing the SSH connection overhead.

I don't know if docs are stored here, but Capistrano has had for a number of months a connection pool which shaves about 70% of the deploy time off most of our scripts here.

It might be worth editing this copy to reflect the inaccuracy rather than throwing another FOSS project under the bus. 

No worries either way, feel free to close the issue. I had a similar discussion with the Vlad team a number of years ago where they were claiming something "sucked less than Capistrano".

We're all in it together as they say!

**Comment by d4be4st** [comment]
would love a PR for this as we stoped using Capistrano long ago and do not know the changes :(
