### ISSUE TITLE
Why don't you also read the `.bash_profile`?

### ISSUE THREAD

**Issue by jmuheim** [mina-deploy/mina#176]
My hoster lets me activate Ruby 2.1 by adding some lines to my `.bash_profile`:

```
export PATH=/package/host/localhost/ruby-2.1.1/bin:$PATH
export PATH=$HOME/.gem/ruby/2.1.0/bin:$PATH
```

I needed hours to make Mina work because it didn't find bundler itself, as `.bash_profile` is only read by non-interactive shells, so Mina used the "wrong" path.

I fixed the issue by doing this:

```
task :environment do
  queue %[echo '-----> Loading environment']
  queue %[source ~/.bash_profile]
end
```

Maybe this should be mentioned somewhere? Would it be a problem to always automatically load `.bash_profile`?

Thanks for Mina, it's really nice tool and soooo fast! :+1:

**Comment by d4be4st** [comment]
this is shell problem

similar issue: #311
