### ISSUE TITLE
automatically use local rvm version

### ISSUE THREAD

**Issue by cschell** [mina-deploy/mina#182]
I currently have to do something like this to get mina to automatically use the project's ruby version from its [.ruby-version](http://rvm.io/workflow/projects#project-file-ruby-version):

```ruby
invoke :"rvm:use[#{`cat .ruby-version`.strip}]"
```

Shouldn't there be a way like `invoke :"rvm:use_local"` to prevent duplication?

**Comment by d4be4st** [comment]
would love a PR for this as we do not use rvm :(
