### ISSUE TITLE
Foreman is creating the init scripts with the previous release

### ISSUE THREAD

**Issue by caarlos0** [mina-deploy/mina#185]
I was expecting some weird issues in my application, so I decided to dive in the foreman generated startup scripts, and found this:

> cat /etc/init/app-web-1.conf

```
start on starting app-web
stop on stopping app-web
respawn

exec su - deploy -c 'cd /var/www/wealcash.com/releases/20; export TONS_OF=VARIABLES;  bundle exec puma -C ./config/puma.rb config.ru -e production >> /var/www/app.com/shared/log/web-1.log 2>&1'
```

> cat /etc/init/app-worker-1.conf

```
start on starting app-worker
stop on stopping app-worker
respawn

exec su - deploy -c 'cd /var/www/wealcash.com/releases/20; export TONS_OF=VARIABLES;  bundle exec sidekiq -C config/sidekiq.yml -e production >> /var/www/app/shared/log/worker-1.log 2>&1'
```

It looks fine, except that the current release is `21`.

I am also expecting some really weird behavior, like if foreman never stops putting more services up.. looks like some infinite loop somewhere.

Any advice on that?
I followed the docs about the foreman module.

Cheers

**Comment by d4be4st** [comment]
moved forma to https://github.com/mina-deploy/mina-foreman
