### ISSUE TITLE
Simple `mina git:clone` fails on step "Using git branch 'master'"

### ISSUE THREAD

**Issue by brandondrew** [mina-deploy/mina#200]
local $ mina -v git:clone

    -----> Cloning the Git repository
    $ git clone "https://brandondrew@github.com/SpartanNash/ad-reports-insite.git" "/var/www/vhosts/test.insite.spartannash-dev.com/scm" --bare
    Cloning into bare repository '/var/www/vhosts/test.insite.spartannash-dev.com/scm'...
    Password for 'https://brandondrew@github.com':
    remote: Reusing existing pack: 761, done.
    Receiving objects: 100% (761/761), 1.98 MiB | 604.00 KiB/s, done.
    remote: Total 761 (delta 0), reused 0 (delta 0)
    Resolving deltas: 100% (299/299), done.
    Checking connectivity... done.
    -----> Using git branch 'master'
    $ git clone "/var/www/vhosts/test.insite.spartannash-dev.com/scm" . --recursive --branch "master"
    fatal: destination path '.' already exists and is not an empty directory.
    Connection to spartand3 closed.

     !     Command failed.
           Failed with status 32768
    local $

The same results are obtained by running the same commands on the server, so it looks like Mina is not sending the correct commands in the first place.  For instance, when it runs `git clone "/var/www/vhosts/test.insite.spartannash-dev.com/scm" . --recursive --branch "master"`, `.` is the main `:deploy_to` directory.  That doesn't sound right—shouldn't it be specifying a different directory?  (Certainly Git thinks it shouldn't be cloning into that location!)

My deploy.rb file contains

```ruby
require 'mina/git'

set :domain, 'spartand3' # host, NOT domain!
set :deploy_to, '/var/www/vhosts/test.insite.spartannash-dev.com'
set :repository, 'https://brandondrew@github.com/SpartanNash/ad-reports-insite.git'
set :branch, 'master'
set :user, 'bzisad0'

task :environment do
  queue! %[echo "-----> This is a test from the :environment task."]
  queue  %[echo "-----> You can safely ignore it."]
end

task :setup => :environment do
  queue! %[echo "-----> This is a test from the :setup task."]
  queue  %[echo "-----> You can safely ignore it."]
end

desc "Deploys the current version to the server."
task :deploy => :environment do
  deploy do
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'

    to :launch do
      queue! %[echo "-----> This is a test from the :launch task."]
      queue  %[echo "-----> You can safely ignore it."]
    end
  end
end
```

**Comment by d4be4st** [comment]
Seems to be fixed in future versions
