### ISSUE TITLE
Carrierwave: how to share public/uploads path?

### ISSUE THREAD

**Issue by jmuheim** [mina-deploy/mina#214]
I simply added `public/uploads` to `:shared_paths` like this:

```
set :shared_paths, ['config/database.yml', 'log', 'tmp', 'public/uploads']
```

Then in `task setup: :environment` added:

```
queue! %[mkdir -p "#{deploy_to}/shared/public/uploads"]
queue! %[chmod g+rx,u+rwx "#{deploy_to}/shared/public/uploads"]
```

Is this the correct approach?

**Comment by KleysonCarreira** [comment]
Muito obrigado!

**Comment by folivi** [comment]
Getting error  403 with this in my rails 5 app

**Comment by jarvisjohnson** [comment]
For anyone look at this now, the current method is:

`set :shared_dirs, fetch(:shared_dirs, []).push('public/system')` (for Paperclip) or
`set :shared_dirs, fetch(:shared_dirs, []).push('public/uploads')` (for Carrierwave)

I also need to create the directory to symlink to:

`mkdir ~/app/shared/public/system` or `mkdir ~/app/shared/public/uploads`
