### ISSUE TITLE
Queue commands in different buckets using sub-tasks

### ISSUE THREAD

**Issue by paulRbr** [mina-deploy/mina#228]
__Hello!__

I've been through a behaviour that I didn't expect with the `to` helper.

Indeed when invoking a task in a `to :launch` bucket, I expected the `queue`d commands from that given task to be queued in the `:launch` bucket.
```ruby
to :launch do
  invoke :'restart:passenger'
end
```

But instead I got:
```ruby
assert !commands.empty?
assert commands(:launch).empty?
```

I understand that the goal is to keep the `rake` logic by simply `invoke_task` on `rake` but I think `mina` should keep track of the bucket in which the tasks are invoked.

What do you think?

**Comment by d4be4st** [comment]
where did you invoke those asserts? 
because commands(:launch) is only availiable inside deploy do block
