### ISSUE TITLE
logfile on server?

### ISSUE THREAD

**Issue by j6s** [mina-deploy/mina#242]
Hello. I would like to write a deploy log to my server, to see who deploy what and when.

I am not shure if there are variables defined for the stuff i would need for it, thats why I am asking. The variables I would need are: name (username or git name), current git hash, (current git commit message).

I would like to do something like this:
```ruby
queu "echo '[$(date)] #{hash} (#{message}) deployed by #{username}' > #{deploy_to}/deploy.log"
```

This might be a very special usecase, but I would appreciate your help.

btw, Thanks for the value mina is giving us. We are using it for about 3 months now and are probably about 1k-2k deploys in. So much time saved. Thanks guys

**Comment by d4be4st** [comment]
Hi @thephpjo sorry for the long response, i do not know if you figured it out how to do this but here is an example:

```
desc "latest commit"
task :latest_commit => :environment do
  queue  %[cd #{deploy_to}/scm]
  queue  %[echo "[$(date)] $(git log -1 --pretty=%h) ($(git log -1 --pretty=%B)) deployed by $(git log -1 --pretty=%cn)"  > #{deploy_to}/deploy.log]
end
```
