### ISSUE TITLE
sudo for foreman

### ISSUE THREAD

**Issue by pencilcheck** [mina-deploy/mina#243]
https://github.com/sstephenson/rbenv/issues/127

As mentioned in the issue above, foreman with rbenv doesn't work since sudo changes the env, but there is a workaround, just change

sudo_cmd to `sudo $(rbenv which foreman)`
and remove the `bundler exec foreman` in the export command as appropriately however I don't know if this is the best solution.

**Comment by d4be4st** [comment]
moved to https://github.com/mina-deploy/mina-foreman
