### ISSUE TITLE
link_shared_paths links to user folder

### ISSUE THREAD

**Issue by stereodenis** [mina-deploy/mina#248]
when I execute `mina deploy:link_shared_paths` this command
`echo_cmd(%{ln -s "#{deploy_to}/#{shared_path}/#{file}" "./#{file}"})`
links files to `/home/user` folder instead of current release folder

**Comment by d4be4st** [comment]
That is a problem, because when you run this link_shared_paths command as a standalone you wont cd to current release folder.

If you do not want the link_shared_paths to happen inside a deploy script, you can create a new task like this:

```
task :my_link_shared_paths => :environment do
  queue %[cd #{deploy_to}/#{current_path}]
  invoke :'deploy:link_shared_paths' 
end
````

**Comment by stereodenis** [comment]
@d4be4st 
"when you run this link_shared_paths command as a standalone you wont cd to current release folder"
is it normal or it is a bug?

**Comment by stereodenis** [comment]
@d4be4st task `mina deploy:link_shared_paths`
I think it should work with current release
but it doesn't

**Comment by d4be4st** [comment]
The thing is that mina does not know what current release path is outside of deploy task. That is not stored anywhere. We could assume that it is the latest release but that might not be the case as you can symlink your current folder to any of the release folders

**Comment by stereodenis** [comment]
ok
