### ISSUE TITLE
Ability to overwrite the default tasks

### ISSUE THREAD

**Issue by jb-san** [mina-deploy/mina#26]
are there plans to make it possible to overwrite the default tasks ?
I know I can fork it and make the changes, but I think its better to keep the forks to a minimum..

---

like if I use git
I think on the initial setup, it should just clone the repository, but on subsequent deploys it should just do a git fetch origin,

when I try to overwrite the git:clone task I get

```
-----> Cloning the Git repository
fatal: destination path '.' already exists and is not an empty directory.
```

no matter what i put in the 

``` ruby
namespace :git do
  desc "Clones the Git repository to the release path."
  task :clone do
    queue "echo $PATH"
  end
end
```

it does echo the $PATH though..

**Comment by kml** [comment]
For example to override log task from mina/rails put this inside config/deploy.rb:

```ruby
Rake::Task["log"].clear

desc 'Tail log from server'
task :log do
  set :execution_mode, :exec
  in_path "#{fetch(:shared_path)}/log" do
    command %{tail -F #{fetch(:rails_env)}.log /var/log/supervisor/puma.out.log}
  end
end
```
