### ISSUE TITLE
Can I safely embed `.env` in the Mina deploy script?

### ISSUE THREAD

**Issue by mhluska** [mina-deploy/mina#265]
I'm currently doing this:

```
desc "Copies sensitive file data to the deploy script."
task :copy_dotenv do
  dotenv = File.read('.env')
  dotenv_production = File.read('.env.production')

  queue %[echo -n "#{dotenv}" | tr -d ' ' > "#{deploy_to}/#{shared_path}/.env"]
  queue %[echo -n "#{dotenv_production}" | tr -d ' ' > "#{deploy_to}/#{shared_path}/.env.production"]
end
```

Which embeds all my keys in the deploy script. Is this stupid or safe? I imagine it's fine since the deploy script is transmitted via SSH.

**Comment by d4be4st** [comment]
I think a better solution would be to create a shared/.env file in your deploy_to path. Than you can add '.env' to shared_paths which will link your .env on each deploy. Same as config/database.yml or secrets.yml file
