### ISSUE TITLE
Unicorn not starting when using mina

### ISSUE THREAD

**Issue by nmora** [mina-deploy/mina#272]
When I run mina unicorn:start, I get an error:  /home/deployer/xxx-api/releases/7 not found . I am certain that directory exists on the server. Can you kindly take a look to know if it is a problem with mina or mina-unicorn.

```
Navaratans-Mac-mini:xxx-api navtech$ RAILS_ENV=production mina unicorn:start --verbose
-----> Loading environment
$ source ~/.bashrc
-----> Loading rbenv
$ export RBENV_ROOT="$HOME/.rbenv"
$ export PATH="$HOME/.rbenv/bin:$PATH"
$ eval "$(rbenv init -)"
-----> Starting Unicorn...
/home/deployer/xxx-api/releases/7 not found
Connection to 104.131.92.185 closed.

 !     Command failed.
       Failed with status 2560
```

**Comment by kot-begemot** [comment]
Facing exactly same issue

```bash
$ mina unicorn:start
-----> Loading environment
-----> Loading rbenv
-----> Starting Unicorn...
/home/project/www/releases/2 not found
Connection to 178.132.203.73 closed.

 !     Command failed.
       Failed with status 2560
```

**Comment by kot-begemot** [comment]
Ok, i figured it. Mina-unicorn relies on bundle_config variable

https://github.com/openteam/mina-unicorn/blob/master/lib/mina/unicorn/utility.rb#L78

It is not defined neither in mina, nor in mina-unicorn.
Add a line `set :bundle_gemfile,  "#{deploy_to}/#{current_path}/Gemfile"` to your deploy file, and it will be working.

**Comment by nmora** [comment]
fixed the issue

by modifying config/deploy.rb
from 
```
set :unicorn_pid, "#{deploy_to}/shared/pids/unicorn.pid"
```
to 
```
set :unicorn_pid, "/home/deployer/pids/unicorn.pid"
```

**Comment by d4be4st** [comment]
Mina does not have unicorn support out of the box.
I think you need to post this to https://github.com/scarfacedeb/mina-unicorn
