### ISSUE TITLE
Hangs on confirming host key phase.

### ISSUE THREAD

**Issue by x-yuri** [mina-deploy/mina#277]
If host key hasn't yet been cached, the whole thing hangs. Or more precisely, it waits for you to type "yes<Enter>". But there's probably no way one can do it. Well, one can do it, or so it seems. You type "yes" and press `Enter`. And it looks like it got your answer. But no, it's not gonna progress any further.

The issue must be because `mina` [redirects `stdin`](https://github.com/mina-deploy/mina/blob/v0.3.2/lib/mina/exec_helpers.rb#L20), but `ssh` reads from `/dev/tty`. Not sure if there's anyting one can do.

**Comment by chauncey-garrett** [comment]
+1

**Comment by d4be4st** [comment]
We found a workaround for this, for now.
In the v0.3.2 you can use `mina ssh` command which will open a normal ssh where you can type yes.
Then disconnect and use setup/deploy

**Comment by chauncey-garrett** [comment]
That would work but IIRC there is no fallback. Mina just hangs and the enduser is left wondering why...

**Comment by zmckenzie** [comment]
Which term mode are you using? Pretty will not work for STDIN you'll need to change it to system if you want to be able to interact.

```
set :term_mode, :system
```

**Comment by d4be4st** [comment]
Fixed in the next release
