### ISSUE TITLE
unable to run rails console

### ISSUE THREAD

**Issue by blackbiron** [mina-deploy/mina#279]
i tried to run following commands:
`mina "rails[console]" to=production` from my local machine, and
`RAILS_ENV="production" bundle exec rails console` on remote server

they both returning this as result:
    
    Usage:
      rails new APP_PATH [options]

    Options:
      -r, [--ruby=PATH]                                      # Path to the Ruby binary of your choice
                                                             # Default: /home/deployer/.rbenv/versions/2.1.3/bin/ruby
      -m, [--template=TEMPLATE]                              # Path to some application template (can be a filesystem path or URL)
          [--skip-gemfile], [--no-skip-gemfile]              # Don't create a Gemfile
      -B, [--skip-bundle], [--no-skip-bundle]                # Don't run bundle install
      -G, [--skip-git], [--no-skip-git]                      # Skip .gitignore file
          [--skip-keeps], [--no-skip-keeps]                  # Skip source control .keep files
      -O, [--skip-active-record], [--no-skip-active-record]  # Skip Active Record files
      -V, [--skip-action-view], [--no-skip-action-view]      # Skip Action View files
      -S, [--skip-sprockets], [--no-skip-sprockets]          # Skip Sprockets files
          [--skip-spring], [--no-skip-spring]                # Don't install Spring application preloader
      -d, [--database=DATABASE]                              # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                                             # Default: sqlite3
      -j, [--javascript=JAVASCRIPT]                          # Preconfigure for selected JavaScript library
                                                             # Default: jquery
      -J, [--skip-javascript], [--no-skip-javascript]        # Skip JavaScript files
          [--dev], [--no-dev]                                # Setup the application with Gemfile pointing to your Rails checkout
          [--edge], [--no-edge]                              # Setup the application with Gemfile pointing to Rails repository
      -T, [--skip-test-unit], [--no-skip-test-unit]          # Skip Test::Unit files
          [--rc=RC]                                          # Path to file containing extra configuration options for rails command
          [--no-rc], [--no-no-rc]                            # Skip loading of extra configuration options from .railsrc file

    Runtime options:
      -f, [--force]                    # Overwrite files that already exist
      -p, [--pretend], [--no-pretend]  # Run but do not make any changes
      -q, [--quiet], [--no-quiet]      # Suppress status output
      -s, [--skip], [--no-skip]        # Skip files that already exist

    Rails options:
      -h, [--help], [--no-help]        # Show this help message and quit
      -v, [--version], [--no-version]  # Show Rails version number and quit

    Description:
        The 'rails new' command creates a new Rails application with a default
        directory structure and configuration at the path you specify.

        You can specify extra command-line arguments to be used every time
        'rails new' runs in the .railsrc configuration file in your home directory.

        Note that the arguments specified in the .railsrc file don't affect the
        defaults values shown above in this help message.

    Example:
        rails new ~/Code/Ruby/weblog

        This generates a skeletal Rails installation in ~/Code/Ruby/weblog.
        See the README in the newly created application to get going.

i'm not sure whether this caused by mina or not but i'm experiencing this on 2 projects which using mina

**Comment by d4be4st** [comment]
You can use
    
    mina console

But this has nothing to do with mina. Probably with rails. Did you try upgrading rails?

**Comment by blackbiron** [comment]
i tried `mina console` but produce same output as before. i'm using rails 4.1.9 with ruby 2.1.3

**Comment by d4be4st** [comment]
If you are getting the same error for running

    RAILS_ENV=production bundle exec rails console

on the server directly, than it is a rails error. 

you can try this: http://stackoverflow.com/questions/3744567/typing-rails-console-doesnt-start
Or removing all files in your bin and vendor/bundle folder and try deploying again.

Sorry, this is not mina error, closing

**Comment by sebackend** [comment]
I'm facing this problem too, when i trying to run this command from the project folder in the server
`RAILS_ENV=production rails console`

it shows this message
```
The program 'rails' is currently not installed. You can install it by typing:
sudo apt install ruby-railties
```
What am i missing? I have no errors if i run 
`mina console`

But i want to be able to make changes from the project server folder too
