### ISSUE TITLE
Error while precompiling assets **bash: line 232: 21006 Killed**

### ISSUE THREAD

**Issue by hlcfan** [mina-deploy/mina#282]
While it's executing:
`RAILS_ENV="production" bundle exec rake assets:precompile RAILS_GROUPS=assets`

it gives me:
``` bash
I, [2015-03-04T09:39:18.486341 #21006]  INFO -- : Writing /home/hlcfan/leniu/tmp/build-142546194323803/public/assets/sidebar_bg-0a35ab7c07f029d90724d03bb97c4b9f.png
I, [2015-03-04T09:39:18.488875 #21006]  INFO -- : Writing /home/hlcfan/leniu/tmp/build-142546194323803/public/assets/slider1-65b3e5521ac11c47845925b5fbb13360.jpg
I, [2015-03-04T09:39:18.492084 #21006]  INFO -- : Writing /home/hlcfan/leniu/tmp/build-142546194323803/public/assets/slider2-625bee99a44969f73fcb419121688538.jpg
I, [2015-03-04T09:39:18.498015 #21006]  INFO -- : Writing /home/hlcfan/leniu/tmp/build-142546194323803/public/assets/slider3-3b3837a01d4ed5ea8c703e2a9c6ea37b.jpg
I, [2015-03-04T09:39:18.632689 #21006]  INFO -- : Writing /home/hlcfan/leniu/tmp/build-142546194323803/public/assets/admin-307af29ac27a030829bb53a3718d3987.js
bash: line 232: 21006 Killed                  RAILS_ENV="production" bundle exec rake assets:precompile RAILS_GROUPS=assets
! ERROR: Deploy failed.
-----> Cleaning up build
```

Since no error messages to track this problem, I have no idea to fix this.

**Comment by d4be4st** [comment]
Have you tried doing that command locally?

**Comment by hlcfan** [comment]
@d4be4st  it works great locally.

**Comment by d4be4st** [comment]
Hm.. Try to run `mina deploy -v` in verbose mode, and see that it tells you.
Unfortunately i need more information :(

**Comment by d4be4st** [comment]
Oh, @hlcfan  do you have nodejs installed on server or are you using rubyracer gem?

**Comment by hlcfan** [comment]
Yes, Im using `therubyracer` in Gemfile and I dont have nodejs installed on my server

**Comment by d4be4st** [comment]
one more thing you can try is run the command manually on the server, as see what errors it gives you

**Comment by hlcfan** [comment]
@d4be4st Just remove `therubyracer`, use `nodejs` instead, `therubyracer` sucks!

**Comment by TheBrockEllis** [comment]
I ran into this same issue and couldn't find any good answers. Finally figured out that it was my Digital Ocean droplet running out of RAM and the process was being killed. You can read more about my solution [here](http://thebrockellis.com/2017/01/10/Mina-being-killed-by-bash).
