### ISSUE TITLE
Deploy locked without deploy.lock file

### ISSUE THREAD

**Issue by activestylus** [mina-deploy/mina#283]
I've run `mina deploy:force_unlock` and checked my app path. There is no deploy.lock file yet my deploy fails with "ERROR: another deployment is ongoing"

Using mina 0.3.2 with ruby 2.1.2

**Comment by 13k** [comment]
I've run into this by accidentally running two `deploy` blocks in the same flow. Maybe that's your case too.

Check with `mina -S <deploy or your task>` if the lock isn't being written twice.

**Comment by d4be4st** [comment]
no more information, closing
