### ISSUE TITLE
bash : bundle: command not found

### ISSUE THREAD

**Issue by icn** [mina-deploy/mina#290]
I can run the command on the sever using the deploy user (st in mina)
'bundle install --without development:test --path "./vendor/bundle" --deployment' with no issue at all

**Comment by d4be4st** [comment]
not a mina issue, your .bashrc is not properly set up.

please make sure your env/rbenv/rvm in .bashrc is above this line:

    # If not running interactively, don't do anything
    [ -z "$PS1" ] && return
