### ISSUE TITLE
Best way to reload nginx.conf

### ISSUE THREAD

**Issue by Epigene** [mina-deploy/mina#291]
Hi, not a bug report, just wondering how to best do things.

I am deploying a rails app running on puma behind nginx.

So far I have a task for linking the app's nginx.conf into sites-enabled like so:

```
desc "Takes care of nginx conf"
task :nginx_link => :environment do
  queue! %[ln -nfs /home/deployer/apps/#{app_name}/current/config/deploy/nginx.conf /etc/nginx/sites-enabled/#{app_name}]
  queue! %[ln -nfs /home/deployer/apps/#{app_name}/current/config/deploy/nginx.conf /etc/nginx/sites-available/#{app_name}]
  #queue! %[sudo nginx -s reload]
end
```

My problem is that the nginx configuration does not seem to reload to take the latest changes into account so I need to run `sudo nginx -s reload` which requires me to enter the sudo password.

I am looking into setting up this command for the **deployer** user to run without password following http://askubuntu.com/questions/73864/how-to-modify-a-invalid-etc-sudoers-file-it-throws-out-an-error-and-not-allowi

Am I on the right track or perhaps there is a way to pass sudo password to mina in deploy.rb and have it pass automagically?

Thanks!

**Comment by d4be4st** [comment]
We have for our servers created a few lines in sudoer file that allow deploy user to reload nginx.

    deploy ALL=(ALL) NOPASSWD: /etc/init.d/nginx reload

and added an alias to .bashrc file
    
    alias nginx-reload='sudo /etc/init.d/nginx reload'

now our deploy users can reload nginx without sudo privileges

**Comment by Epigene** [comment]
Yup, ended up doing it like that.

Note to others, use `sudo visudo -f /etc/sudoers.d/deployer` to enter the line adding interface correctly.

**Comment by Abbas** [comment]
tes saja lah
htlm code
<a href="http://www.undangancinta.com">undangan pernikahan</a>
<a href="http://www.undangancinta.com">undangan pernikahan unik</a>
<a href="http://www.undangancinta.com">undangan pernikahan unik</a>


ini cuma pake ling
http://www.undangancinta.com

bb code 
[url=http://www.undangancinta.com]undangan pernikahan[/url]
[url=http://www.undangancinta.com]undangan pernikahan simple[/url]
[url=http://www.undangancinta.com]undangan pernikahan unik[/url]

᯸ѨĬ
