### ISSUE TITLE
when Skipping asset precompilation, it copied assets to wrong path

### ISSUE THREAD

**Issue by icn** [mina-deploy/mina#293]
it copies "/var/www/rails/releases/4/public/assets"  to "/var/www/rails/releases/5/public" Isn's it supposed to copy it to /var/www/rails/releases/5/public/assets if Skipping asset precompilation?

Thanks

**Comment by d4be4st** [comment]
No, because if you created assets folder in your public folder on purpose, you do not want the files to be copied to /public/assets/assets

http://www.computerhope.com/unix/ucp.htm

    if the directory files-backup already exists, the directory files will be placed inside;
    if files-backup does not already exist, it will be created and the contents of the files directory will be placed inside it.

**Comment by icn** [comment]
I didn't create the assets fold. IT was all generated by standard rails assest pipeline
