### ISSUE TITLE
More control on command verbosity

### ISSUE THREAD

**Issue by fgarcia** [mina-deploy/mina#294]
I find some tasks like `rails:assets_precompile` slightly more verbose than necessary.

The current implementation will print every generated asset and as an alternative implementation I am doing this:

    # invoke :'rails:assets_precompile'
    queue 'echo "-----> Precompiling asset files"'
    queue "bundle exec rake assets:precompile 2>&1 | grep -v 'INFO --' || true"

**Comment by d4be4st** [comment]
This is an issue with rake assets:precompile as it outputs to STDERR instead of STDOUT.

**Comment by fgarcia** [comment]
Yes, showing always any STDERR seems a sane default. I am no longer sure this is such a great feature

Furthermore, this might encourage people to always generate all assets from scratch whenever they should be shared between each deploy :-/
