### ISSUE TITLE
Git helper for pending push

### ISSUE THREAD

**Issue by fgarcia** [mina-deploy/mina#295]
I believe that some type of warning or error message when trying to deploy with pending commits would be a sane default.

I use this little helper that prevents my most frequent deployment problem. I leave to the maintainers deciding if this is useful and if it should be a default or a helper function.

    def no_push_pending!
      pending = system "[ $(git log origin/master..master | wc -l) -ne 0 ]"
      fail "Pending git push!" if pending
    end

    desc "Deploys the current version to the server."
    task :deploy => :environment do
      no_push_pending!
      deploy do
        invoke :'git:clone'
        invoke :'deploy:link_shared_paths'
        ....
      end
    end

Obviously the current helper is limited because it only considers the 'master' branch.

**Comment by 13k** [comment]
You could improve it by using the `branch` setting instead of hard-coding master

**Comment by d4be4st** [comment]
would love a PR for this. and using `branch` setting :)
