### ISSUE TITLE
mina don't support deployment by tag

### ISSUE THREAD

**Issue by huanzhang** [mina-deploy/mina#296]
When we prepare to release a version of our product, generally, we will create a tag on the release branch and want to deploy according to the tag. But mina does not support tag deployment something like:
```
set :tag, 'v1.0.1'
```
Could mina support this?

**Comment by 13k** [comment]
Try using `set :commit, 'v1.0.1'`

**Comment by czj** [comment]
We have the same issue with our app. We use tags to avoid creating `staging` branch every time we wish to deploy a specific version on the staging server.

Here is the code we used:

```ruby
namespace :git do
  desc "Clones the Git repository to the release path."
  task :clone do
    queue %{
      if [ ! -d "#{deploy_to}/scm/.git" ]; then
        echo "-----> Cloning the Git repository"
        #{echo_cmd %[git clone "#{repository}" "#{deploy_to}/scm"]}
      else
        echo "-----> Fetching new git commits"
        #{echo_cmd %[cd "#{deploy_to}/scm" && git pull --all --prune --tags]}
      fi
    }

    in_directory "#{deploy_to}/scm" do
      queue %{ echo "-----> Using this git commit :" && echo }
      queue %{ #{echo_cmd %[git show -s --oneline #{branch}]} && echo }
    end

    queue %{ echo "-----> Using git branch '#{branch}'" }
    queue %{ #{echo_cmd %[git archive --format=tar "--remote=#{deploy_to}/scm" #{branch} | tar xf -]} }
  end
end
```

By the way, this doesn't work with a bare repository (we tried but had way too many issues).

The `git archive` command allows us to clone the file a in directory without deleting the `.git` repository afterwards.

**Comment by d4be4st** [comment]
@13k answered the question correctly. closing
