### ISSUE TITLE
rvm:use without environment parameter

### ISSUE THREAD

**Issue by ralfebert** [mina-deploy/mina#297]
rvm:use[] requires an environment which is unnecessary when the project has a .ruby-version file.

Workaround:

	task :environment do
	  queue %{
	      source /usr/local/rvm/scripts/rvm
	      rvm use || exit 1
	    }
	end

**Comment by d4be4st** [comment]
Would love a PR with this.
Thx

**Comment by ralfebert** [comment]
Looking a bit more into this, I found out that the workaround doesn't work - it does not take the ruby version according to the .ruby-version file but the default ruby on the system.

I found no way to set the environment according to the .ruby-version file in the current deploy commit - in the environment task the git commit is not cloned yet; and later after cloning; environment variables cannot be set (after queuing a command, the changed environment seems to be thrown away).

I worked around this issue by reading the .ruby-version according to the local file:

~~~ruby
task :environment do
  ruby_version = File.read('.ruby-version').strip
  raise "Couldn't determine Ruby version: Do you have a file .ruby-version in your project root?" if ruby_version.empty?
  queue %{
    source /etc/profile.d/rvm.sh
    rvm use #{ruby_version} || exit 1
  }
end
~~~

Do you see a way to do this in a more clean way using the file in the deploy commit on the server? If we find a clean solution, I would take the time to create a PR to add this to the rvm task.

**Comment by ralfebert** [comment]
btw, here is a full guide to the setup for which I cooked up this workaround: http://www.ralfebert.de/tutorials/rails-deployment/

**Comment by hernandesbsousa** [comment]
:+1: for finding a solution to this problem, I had the exact same issue and the workaround @ralfebert provided worked as a charm, thanks!
