### ISSUE TITLE
secrets.yml in shared_paths by default

### ISSUE THREAD

**Issue by ralfebert** [mina-deploy/mina#298]
For Rails >4.1, 'mina init' would be more consistent if the generated deploy.rb would treat the ['secrets.yml'](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#config-secrets-yml) file in the same way as the 'config/database.yml' as it's not recommended to configure the production settings in the repository, like:

```
set :shared_paths, ['config/database.yml', 'config/secrets.yml', 'log']

task :setup => :environment do
  # ...
  queue! %[touch "#{deploy_to}/#{shared_path}/config/database.yml"]
  queue! %[touch "#{deploy_to}/#{shared_path}/config/secrets.yml"]
  queue  %[echo "-----> Be sure to edit '#{deploy_to}/#{shared_path}/config/database.yml and secrets.yml'."]
end
```

**Comment by d4be4st** [comment]
thx for this, will be added to next release
