### ISSUE TITLE
Why does rails:db_migrate run on the previous release?

### ISSUE THREAD

**Issue by ivanyv** [mina-deploy/mina#300]
Forgive me if I'm missing something obvious (though I think not, I've been reading the docs and source), but why does `rails:db_migrate` run on the `current` directory before linking to the new version?

Shouldn't there be a `release_path` property where it should be run?

**Comment by d4be4st** [comment]
if you are running the default deploy.rb script that mina generates, db_migrate is run in default scope

``` ruby
    task :deploy => :environment do
      deploy do
        ...
        invoke :'rails:db_migrate'
        ...
      end
    end
```

this will end up in command(:default) array. If you then take a look at `deploy.sh.erb` you will see that that command array is run inside $build_path directory

``` ruby
    <% prepare = commands(:default).map { |s| "(\n\n#{indent 2, s}\n\n)" }.join(" && ") %>
    ...
    (
      echo "-----> Creating a temporary build path"
      <%= echo_cmd %[touch "#{lock_file}"] %> &&
      <%= echo_cmd %[mkdir -p "$build_path"] %> &&
      <%= echo_cmd %[cd "$build_path"] %> &&
      (
    <%= indent 4, (prepare.empty? ? "true" : prepare) %>
      )
    ) &&
```

**Comment by ivanyv** [comment]
That's what I thought, but look at this line in the https://github.com/mina-deploy/mina/blob/master/lib/mina/rails.rb#L72 file:

    queue echo_cmd %[cd "#{deploy_to!}/#{current_path!}" && #{command} #{arguments}]

Doesn't that specifically make the commands run on the current path, i.e., the previous release?

**Comment by d4be4st** [comment]
That lambda is not used inside tasks which are used for db_migrate or other which are invoked in deploy script.

This one is used in deploy script:
https://github.com/mina-deploy/mina/blob/master/lib/mina/rails.rb#L108

**Comment by ivanyv** [comment]
Ah, confusing but I'm beginning to understand.

Still, say I want to run my own commands inside the build_path? I haven't found a way of doing that yet :(

**Comment by d4be4st** [comment]
Just queue/invoke them among others in `deploy do` block

``` ruby
    task :deploy => :environment do
      deploy do
        ...
        queue "command my_something"
        invoke :'rails:db_migrate'
        ...
      end
    end
```

**Comment by ivanyv** [comment]
That was what I tried. I will test this further, maybe it's a difference between invoking a task and using queue directly.

**Comment by ivanyv** [comment]
I'm not sure what I was doing wrong before, but it seems you're 100% right. Sorry for the time waster!
