### ISSUE TITLE
sudo command in configuration

### ISSUE THREAD

**Issue by caulfield** [mina-deploy/mina#302]
Due to use several rubies manager and commands with sudo required (for example foreman). What do you think about universal sudo command. I set up my rbenv using rbenv-sudo (https://github.com/dcarley/rbenv-sudo) and it would be cool to set something like 

`set :sudo, 'rbenv sudo'`

There are a lot of issue there about foreman problems and potential problems with new plugins

**Comment by d4be4st** [comment]
Would love a PR with this as we do not have much time to invest in mina unfortunately :(
