### ISSUE TITLE
Whenever tasks use old release in readme example

### ISSUE THREAD

**Issue by biomancer** [mina-deploy/mina#304]
Using `invoke :'whenever:update'` in `deploy` block causes this task to run from old release and to use old `schedule.rb`. It uses new build only after current symlink is updated, for example in `to :launch` block.

Probably either  `cd #{deploy_to!}/#{current_path!} ;` should be removed from these tasks or, if there is some reason for this cd, readme example should be updated to something like that:

     require 'mina/whenever'

     task :deploy => :environment do
       deploy do
         ...
         to :launch do 
           invoke :'whenever:update'
           ...
         end         
       end
      end

I may create pull request if I understood everything correctly.

**Comment by bastengao** [comment]
I also have this issue.

**Comment by d4be4st** [comment]
invoke :'whenever:update' is supposed to be run in :launch block
will update readme to reflect that
