### ISSUE TITLE
Whenever override crontab config when multiple applications be deployed to one domain

### ISSUE THREAD

**Issue by bastengao** [mina-deploy/mina#305]
Current whenever identifier is `#{domain}_#{rails_env}`,  it conflicts when multiple applications with same rails_env be deployed to one domain. Whenever capistrano build-in identifier is `#{application}_#{stage}`, that is good.

**Comment by d4be4st** [comment]
You can change your domain for the staging server.

lets say you have a example.com and staging.example.com,
you should put the domain for the staging to staging.example.com :)

**Comment by bastengao** [comment]
@d4be4st It works partly. There is a web app and another background app in our system. There will be 4 apps in one server if the server serves  two stages. Should I configure 4 domains for each app?

**Comment by d4be4st** [comment]
I see what you mean.
Would something like this help you? I just need a better name for that variable :)

https://github.com/mina-deploy/mina/commit/148b9e9853766f7b7f24fe311987100c19be064e

**Comment by bastengao** [comment]
@d4be4st :+1:  It's good, tank you. I could override `whenever_name` variable in order to avoid conflicts.

**Comment by d4be4st** [comment]
look for it in the next release :)
