### ISSUE TITLE
Mina ssh doesn't load bash_profile?

### ISSUE THREAD

**Issue by jmuheim** [mina-deploy/mina#311]
I load in my .bash_profile ruby 2.2 (default is 1.8.7). When normalling ssh'ing, it works, but when doing `mina ssh`, it doesn't:

```
$ ssh a4aa2@bellatrix.uberspace.de
You have new mail in folder /home/a4aa2/Maildir.
Last login: Mon May  4 12:39:30 2015 from 212.25.11.95
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
$ exit
logout
Connection to bellatrix.uberspace.de closed.
$ mina ssh
$ ruby -v
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
[a4aa2@bellatrix rails]$ 
```

**Comment by JuanitoFatas** [comment]
I think so. I `source` it in `environment` task.

```
task :environment do
  queue 'source ~/.bash_profile'
end
```

**Comment by d4be4st** [comment]
that is because of how ssh works, mina does not run ssh interactively

http://askubuntu.com/a/121075

**Comment by sintro** [comment]
So, how can we workaround this? It is handy to ssh server with mina's ssh command, but everytime we have to print something like `source ~/.bash_profile` in opened console. Is there any options to perform such commands automatically or to login to interactive shell with mina's ssh?
The @JuanitoFatas way does not work

**Comment by d4be4st** [comment]
Take a look at [FAQ](https://github.com/mina-deploy/mina/blob/master/docs/faq.md#--my_program-not-found-but-is-already-installed) There is more info there on how to fix this
