### ISSUE TITLE
ails:assets_precompile never skips precompilation

### ISSUE THREAD

**Issue by mbajur** [mina-deploy/mina#312]
Hello!
I have a strange problem with one of my quite old apps. I'm currently maintaining about 5 ror apps using mina and just one of them has such problem (while deploy.rb scripts seems to be exact the same).

The thing is, each time i make a deploy, the `rails:assets_precompile` step of my deploy.rb compiles all my assets, no matter if there were any changes or not. In my other apps, that step is skipped if there are no changes so i assume that's there is something wrong with my mina config / rails app.

I'm not quite sure if that's mina fault or not but i've decided to start from here. Have you any idea on how can i debug that or what can i do about that?

Thanks in advance!

**Comment by d4be4st** [comment]
can you give us a `mina deploy -v` output so we can see what is going on?

**Comment by d4be4st** [comment]
One year without response. Closing
