### ISSUE TITLE
Integrate with sitemap generator.

### ISSUE THREAD

**Issue by imgarylai** [mina-deploy/mina#313]
Hello, 
Gem [sitemap_generator](https://github.com/kjvarga/sitemap_generator) has integration with capistrano. However, I want to integrate sitemap generator with mina deployment method. 

This is my code and it works good. Can this be integrated to this gem in the future?

```
namespace :sitemap do

  desc 'Generate sitemap'
  task refresh: :environment do
    queue %[
      echo "-----> Sitemap refresh"
      #{echo_cmd %[#{rake} sitemap:refresh]}
    ]
  end

end
```

**Comment by stereodenis** [comment]
@imgarylai make a gem!

**Comment by d4be4st** [comment]
Better make a mina gem as not all of use use sitemap generator.
