### ISSUE TITLE
assets_precompile will skip when i use  js.erb

### ISSUE THREAD

**Issue by huobazi** [mina-deploy/mina#314]
Hi i have a question, 

when i use js.erb with server side code in it

```
var SomeVar = <%= TIMEZONES_CONSTANTS.to_json %>
```

the task assets_precompile will skip

see also  https://github.com/railsware/js-routes/issues/146

**Comment by d4be4st** [comment]
You are changing TIMEZONES_CONSTANT but not chaging anything in js.erb file?

mina uses diff when checking to see if any assets are changed, and wont pick up this kind of change.

easiest way for you to force a precopile is to add an empty line in your js file :)
