### ISSUE TITLE
can not connect to VPS

### ISSUE THREAD

**Issue by dieuit07** [mina-deploy/mina#319]
```
set :domain, 'x.55.247.4'
set :deploy_to, '/home/test'
set :repository, 'https://abc@bitbucket.org/abc/x.git'
set :branch, 'master'
set :user, 'root'
set :rails_env, 'production'
```

when type: "mina setup"
it require to enter pass connect server. When type then "enter". not think happen and the require password still not disappear.

I echo in the first line in setup. SO I think I not connect server yet.
Is anyone have this problem before?

**Comment by dieuit07** [comment]
I add public_key local to authenticate_user vps. And it work!

**Comment by gabskoro** [comment]
Nice :)
