### ISSUE TITLE
command not found bundle

### ISSUE THREAD

**Issue by dieuit07** [mina-deploy/mina#320]
echo current_user => root
echo rvm -v => rvm not found

login directly by ssh terminal with root.
type "rvm -v" => version
type "bundle -v" => version

**Comment by d4be4st** [comment]
mina uses ssh in non interactive mode. Check your rc files on server tahat rvm is loaded before a line like this:

```
# If not running interactively, don't do anything
[ -z "$PS1" ] && return
```

simillar issue in #269
