### ISSUE TITLE
master failed to start, check stderr log for details

### ISSUE THREAD

**Issue by mkosuri** [mina-deploy/mina#322]
Hi folks,
I am using the mina deployment .
I did not faced this error up to now,I am using the combination of nginx unicorn in digital ocean.
the below is the error log .
-----> Cleaning up old releases (keeping 5)
-----> Build finished
-----> Moving build to releases/192
-----> Updating the current symlink
-----> Launching
-----> Starting Unicorn...
master failed to start, check stderr log for details
bash: line 201: kill: (16544) - No such process
! ERROR: Deploy failed.
-----> Cleaning up build
Deleting release
Unlinking current
OK
Connection to 128.199.82.246 closed.
Nginx server restarting working fine. Unlinking current, this is may be socket issue to connecting the unicorn to nginx. 
Thanks
Madhu

**Comment by flowerett** [comment]
Seems that you have pidfile but no system process with such pid. Try to check it.
Also could you provide some info from unicorn error log?

**Comment by mkosuri** [comment]
Yes thanks its working find thanks
