### ISSUE TITLE
Where to properly invoke rails:db_migrate?

### ISSUE THREAD

**Issue by postmodern** [mina-deploy/mina#323]
The rails:db_migrate task uses `current_path!`, but `current/` will still point to the previous deploy until the deploy task re-symlinks `current/`.

**Comment by d4be4st** [comment]
The rails taksk are meant to be invoked inside deploy scripts as stated here: https://github.com/mina-deploy/mina/blob/master/lib/mina/rails.rb#L128

So you wont be able to run those with

`mina rails:db_migrate`

you can always do

`mina 'rake[db:migrate]'`
