### ISSUE TITLE
Port knocking

### ISSUE THREAD

**Issue by bbnnt** [mina-deploy/mina#324]
I was was wondering if it was possible to use mina with a port knocking behavior setup on a ssh access

( this has to be tagged with "help wanted", I'm sorry I don't know how to add labels)

**Comment by d4be4st** [comment]
I see why not. Mina is just a wrapper around SSH which runs a script on the server.
I has the ability to do a script locally before and after the server script runs, you could knock on some in before_hook of the deploy script.

**Comment by fgarcia** [comment]
Since mina is not the only app you will want to make aware of port knocking, it would be better to use netcat and a proxy script in your global ssh config so every programing using a ssh connection will automagically knock.

https://wiki.uugrn.org/Ssh_knock
