### ISSUE TITLE
Add support for tagging releases

### ISSUE THREAD

**Issue by postmodern** [mina-deploy/mina#326]
I would like to have mina `git tag` the local repository after a successful deploy. This would make it easier to track deploys and differences between them.

**Comment by d4be4st** [comment]
I would love a PR for this. We have little time to work continually on mina unfortunatelly but will take a look at a PR.

**Comment by hollodotme** [comment]
Well, here is what I did:

* Disabled mina's default git clone
* Added a task "checkout_release":

```rb
desc "Checks out the current release tag"
task :checkout_release do
    queue %[git clone -b "#{branch}" "#{repository}" .]
    queue 'git fetch'
    # Read the latest tag an check it out
    queue %[git checkout `git describe --abbrev=0 --tags`]
end
```

* Invoking the task in `deploy do` section:

```rb
desc "Deploys the current version to the server."
task :deploy => :environment do
  deploy do
    # Put things that will set up an empty directory into a fully set-up
    # instance of your project.
    invoke :'checkout_release'

    to :launch do
      invoke :'deploy:cleanup'
    end
  end
end
```

So, before deployment I just have to add a new tag to git an mina will check that out.

May not the most generic solution, but works for me, and maybe helps.

**Comment by d4be4st** [comment]
Closing this issue as we wont be adding this unless someone does a PR.
