### ISSUE TITLE
New setup project cannot deploy, "Failed with status 1 (1)"

### ISSUE THREAD

**Issue by Cofyc** [mina-deploy/mina#328]
I run `mina -S deploy` get deploy script, It contains:

```bash
#!/usr/bin/env bash

# Bail out ASAP
set -e

....

# Determine $previous_path and other variables
[ -h "current" ] && [ -d "current" ] && previous_path=$(cd "current" >/dev/null && pwd -LP)
build_path="./tmp/build-`date +%s`$RANDOM"
version=$((`cat "/var/www/project/last_version" 2>/dev/null`+1))
release_path="releases/$version"
...

```

When getting last version with cat, it failed and exit because of `last_version` file is missing.

`mina setup` should create `last_version` file with 0, or deploy script check file exist or not.

At last, I create this file myself to work around this issue.

**Comment by flowerett** [comment]
That's strange, as ```2>/dev/null``` does exactly what you need - checks if ```last_version``` exists.

```bash
$ cat last_version
cat: last_version: No such file or directory
```

```bash
$ cat last_version 2>/dev/null

```

```bash
$ version=$((`cat "last_version" 2>/dev/null`+1))

$ echo $version
1
```

Could you attach the full error log? (miva deploy -v)

**Comment by Cofyc** [comment]
@flowerett 

Hi, because the generated bash script has `set -e` declaration. The script exits immediately if a command exits with a non-zero status.

```
version=$((`cat "last_version" 2>/dev/null`+1))
```

This can get version 1, but the whole script exits here.

You can test it with this demo script:

```
#!/bin/bash

set -e

cat does_not_exist_file 2>/dev/null

echo "ok"
```

Here is full log of `mina deploy -v`.
```
$ mina deploy -v

 !     Command failed.
       Failed with status 1 (1)
```

**Comment by d4be4st** [comment]
Hm... thx for cacthcing this. Obviously we will have to remove that set -e :(
