### ISSUE TITLE
mina deploy failed with status 1 (256)

### ISSUE THREAD

**Issue by roshan92** [mina-deploy/mina#330]
I run ```mina deploy``` but it fails. Below is the error. 

```
-----> Loading environment
$ source ~/.bashrc
-----> Loading rbenv
$ export RBENV_ROOT="$HOME/.rbenv"
$ export PATH="$HOME/.rbenv/bin:$PATH"
$ eval "$(rbenv init -)"
Connection to 128.199.121.23 closed.

 !     Command failed.
       Failed with status 1 (256)
```

Note: I used to deploy to DO using ubuntu, i don't have this type of issue before but recently I changed to Mac and deploying to DO for the first time and this happens. I tried with few other VPS with the same configuration but the result is still same.

Any help would be appreciated.

**Comment by d4be4st** [comment]
What mina version are you using. and could you please do a
```
mina deploy -v
```

**Comment by roshan92** [comment]
Mina, version v0.3.6

**Comment by d4be4st** [comment]
try updating it to 0.3.7

there is a 'set -e' in the bash script for 0.3.6 which will fail immidiately

**Comment by roshan92** [comment]
Damn it, that was it. All I need is ```gem update mina```.

Thank you very much for saving me from 2 days of stress trying multiple times. I'm relieved now. :smile:

**Comment by tabishiqbal** [comment]
I'm using 0.3.7 and it gives me the same error?
