### ISSUE TITLE
How to change releases directory names from auto increment value to datetime?

### ISSUE THREAD

**Issue by allantatter** [mina-deploy/mina#332]
I'd prefer having datetime value instead of auto incrementing number as the name of the release directory.

For example in format YYYYMMDDhhiiss, 20150810133938 (2015 aug 10, 13:39:38).

Is it possible to configure in Mina configuration (deploy.rb)?

**Comment by scythargon** [comment]
+1

**Comment by scythargon** [comment]
here is the answer:(
https://github.com/MafcoCinco/mina/blob/master/lib/mina/deploy_helpers.rb#L40-L56

**Comment by allantatter** [comment]
Thanks.
