### ISSUE TITLE
Unicorn searching gems in outdated releases

### ISSUE THREAD

**Issue by thiagogsr** [mina-deploy/mina#336]
Hi there

I'm using mina and mina-unicorn to deploy my app, but the unicorn is searching the gems in outdated releases. My current release is 230, but an error is raised because Unicorn did not found the gem in release 204.

My `deploy.rb` is here: https://gist.github.com/thiagogsr/aae6e4f7cbccf0071736

Error:
```
cannot load such file -- /home/user/app/releases/204/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/em_http
```

**Comment by d4be4st** [comment]
Sorry, please redirec this issue to mina-unicorn as that is a 3rd pary plugin.
