### ISSUE TITLE
Allow for files/folders to be excluded from deployments

### ISSUE THREAD

**Issue by marshallford** [mina-deploy/mina#337]
I would appreciate the ability to exclude files and folders from deployments. Mina then would just not copy them from the scm directory to the releases directory. I have considering updating my gitignore however there are files I would like tracked by git but don't want on the public facing web. A quick example would be the deploy.rb file and config folder itself. I do not want that file on the web, but I would want it shared between team members.

**Comment by alfie-max** [comment]
@marshallford You could possibly remove those files/directories in the `:after_hook`

**Comment by d4be4st** [comment]
Mina uses git under the hood. Just remove those files from git.

Or remove the files after completed deploy

**Comment by erusev** [comment]
What would be the simplest way to exclude files / folders (that are not `.gitignore`-d) from deployments?

How do you feel about Mina supporting something similar to [Vercel](https://vercel.com/)'s `.vercelignore` where you can list paths that (are not `.gitignore`-d but) you don't want on remote.
