### ISSUE TITLE
Failed on skipping asset precompilation (after PR #266)

### ISSUE THREAD

**Issue by estum** [mina-deploy/mina#339]
I have the `public/assets` path in the `shared_path` parameter, i.e. `current/public/assets` is linked. After the PR #266 the task is trying to copy this dir to itself and, of course, fails.

**Comment by sschafft** [comment]
I confirm this same issue.

**Comment by d4be4st** [comment]
You mightve commited your assets path to git.

But 1.0.0 should remove this issue
