### ISSUE TITLE
NoMethodError: undefined method `fetch' for false:FalseClass

### ISSUE THREAD

**Issue by dcalixto** [mina-deploy/mina#341]
Someone is having this issue when try to deploy with mina?

rake aborted! NoMethodError: undefined method fetch' for
  false:FalseClass
  /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:35:inresolve_string_connection' /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:25:in spec'
  /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in
  establish_connection' /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/railtie.rb:88:in  block (2 levels) in <class:Railtie>'
  /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:36:in
  instance_eval' /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:36:in  execute_hook'
  /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:26:in
  block in on_load' /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:25:in  each'
  /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:25:in
  on_load' /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/activerecord-3.2.22/lib/active_record/railtie.rb:80:in  block in <class:Railtie>'
  /home/ubuntu/vitrineonline.com/tmp/build-144256120718740/vendor/bundle/ruby/2.2.0/gems/railties-3.2.22/lib/rails/initializable.rb:30:in
  instance_exec'

**Comment by japazminio** [comment]
the same error I have when install canvas lms hepl please

**Comment by AldanaQuintana** [comment]
This helped me:
https://codedecoder.wordpress.com/2012/10/14/undefined-method-fetch-for-falsefalseclass/

Totally forgot that I had database.yml on shared path.

**Comment by gabskoro** [comment]
@dcalixto Can you please confirm if everyhting is ok now? (if its because the database.yml file)
