### ISSUE TITLE
ssh-keyscan issue on `mina setup`

### ISSUE THREAD

**Issue by smlparry** [mina-deploy/mina#344]
I will preface this by saying that I have been able to use Mina all good and had success deploying but had this small issue. 

But when I run `mina setup` I get this error: 
<img width="648" alt="screenshot 2015-09-24 18 40 29" src="https://cloud.githubusercontent.com/assets/7920702/10068933/e8ebdf70-62eb-11e5-804b-49be038794fa.png">

It fails but it is at the last step so it isnt stopping me from doing anything but I was wondering what I am not doing for it to be complaining like this?

**Comment by flowerett** [comment]
Could you provide the output of ```mina setup -v```?

also check if you use latest version and last lines of setup section looks like this:
```
if repository
    repo_host = repository.split(%r{@|://}).last.split(%r{:|\/}).first
    repo_port = /:([0-9]+)/.match(repository) && /:([0-9]+)/.match(repository)[1] || '22'

    queue %[
      if ! ssh-keygen -H  -F #{repo_host} &>/dev/null; then
        ssh-keyscan -t rsa -p #{repo_port} -H #{repo_host} >> ~/.ssh/known_hosts
      fi
    ]
end
```

**Comment by ralfebert** [comment]
I also got the broken example code from mina init version 0.3.7 (referring to a non-existing shell variable $repo).
Replacing it with the code above adding the host to known_hosts worked fine for me.
Couldn't this code go in a task so the deploy.rb script doesn't get so cluttered up with details of setting up the environment?

**Comment by smlparry** [comment]
:+1: to @flowerett suggestion. Fixed the issue.

If you are still interested here was the output of `mina setup -v`

```
-----> Setting up /var/www/mina.com
       $ mkdir -p "/var/www/mina.com"
       $ chown -R `whoami` "/var/www/mina.com"
       $ chmod g+rx,u+rwx "/var/www/mina.com"
       $ cd "/var/www/mina.com"
       $ mkdir -p "releases"
       $ chmod g+rx,u+rwx "releases"
       $ mkdir -p "shared"
       $ chmod g+rx,u+rwx "shared"

       $ ls -       usage: ssh-keyscan [-46Hv] [-f file] [-p port] [-T timeout] [-t type]
l       [host | addrlist namelist] ...
       $ ls -la "/var/www/mina.com"
       total 16
       drwxr-xr-x 4 root root 4096 Sep 28 02:04 .
       drwxr-xr-x 3 root root 4096 Sep 28 02:04 ..
       drwxr-xr-x 2 root root 4096 Sep 28 02:04 releases
       drwxr-xr-x 4 root root 4096 Sep 28 02:04 shared


-----> Done.
       $ mkdir -p "/var/www/mina.com/shared/log"
       $ chmod g+rx,u+rwx "/var/www/mina.com/shared/log"
       $ mkdir -p "/var/www/mina.com/shared/config"
       $ chmod g+rx,u+rwx "/var/www/mina.com/shared/config"
       $ touch "/var/www/mina.com/shared/config/database.yml"
       $ touch "/var/www/mina.com/shared/config/secrets.yml"

-----> Be sure to edit '/var/www/mina.com/shared/config/database.yml' and 'secrets.yml'.

 !     Command failed.
       Failed with status 1 (1)
```

**Comment by yihyang** [comment]
@flowerett thanks for your solution!

**Comment by DannyBen** [comment]
Why is this ticket closed? It seems to be a problem that needs a fix no?
I also just started looking into mina today, and the `mina init` command generated a broken code.

I also agree with @ralfebert that an effort should be made to tuck such clutter away from the deploy.rb wherever possible, so that it stays as "DSLed" as possible.

Is my understanding correct, that I should replace this:
```
  queue %[
    repo_host=`echo $repo | sed -e 's/.*@//g' -e 's/:.*//g'` &&
    repo_port=`echo $repo | grep -o ':[0-9]*' | sed -e 's/://g'` &&
    if [ -z "${repo_port}" ]; then repo_port=22; fi &&
    ssh-keyscan -p $repo_port -H $repo_host >> ~/.ssh/known_hosts
  ]
```

with this:
```
if repository
    repo_host = repository.split(%r{@|://}).last.split(%r{:|\/}).first
    repo_port = /:([0-9]+)/.match(repository) && /:([0-9]+)/.match(repository)[1] || '22'

    queue %[
      if ! ssh-keygen -H  -F #{repo_host} &>/dev/null; then
        ssh-keyscan -t rsa -p #{repo_port} -H #{repo_host} >> ~/.ssh/known_hosts
      fi
    ]
end
```

**Comment by kofronpi** [comment]
I agree with @DannyBen , I encoutered the same problem with mina 0.3.7

**Comment by chriscummings** [comment]
What @DannyBen posted solved my issue. Also 0.3.7.
