### ISSUE TITLE
release_path error deploy faild

### ISSUE THREAD

**Issue by tsaomichael** [mina-deploy/mina#346]
mina deploy -v
-----> Symlinking shared paths
$ mkdir -p "."
$ rm -rf "./log"
$ ln -s "/home/node/pepper_develop/shared/log" "./log"
$ rm -rf "./node_modules"
$ ln -s "/home/node/pepper_develop/shared/node_modules" "./node_modules"
npm WARN prefer global forever@0.15.1 should be installed with -g
npm WARN prefer global mina@1.0.9 should be installed with -g
-----> Deploy finished
-----> Building
-----> Moving build to releases/2
$ mv "$build_path" "$release_path"
$ cd "$release_path"
-----> Build finished
-----> Launching
-----> Updating the current symlink
$ ln -nfs "$release_path" "current"
-----> Launching
$ cd "$release_path"
! ERROR: Deploy failed.
-----> Cleaning up build
Deleting release
$ rm -rf "$release_path"
Unlinking current
$ ln -nfs "$previous_path" "current"
$ rm -f "deploy.lock"

can you help me,thanks?

**Comment by flowerett** [comment]
Seems like your node daemon could not start properly and retuns an error, try to check the log.

**Comment by tsaomichael** [comment]
thanks for your reply.but.my setting below

set :deploy_to, '/home/node/pepper_develop'
set :branch, 'develop'
set :env, 'develop'
set :user, 'node'
set :repository, 'git@bitbucket.org:xxxx/aaaa.git'
set :domain, 'pepper.cofit.me'
set :term_mode, nil
set :shared_paths, ['log', 'node_modules']
# set :forever,"#{deploy_to}/shared/node_modules/forever/bin/forever"

task :setup do
  queue "mkdir -p #{deploy_to}/shared/log"
  queue "chmod g+rx,u+rwx #{deploy_to}/shared/log"

  queue "mkdir -p #{deploy_to}/shared/node_modules"
  queue "chmod g+rx,u+rwx #{deploy_to}/shared/node_modules"
end

desc "Deploys the current version to the server."
task :deploy do
  deploy do
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'
    queue  "npm install"
    to :launch do
      queue "forever stopall"
      queue "forever start bin/www"
    end
  end
end

**Comment by Freeza91** [comment]
release_path isn't suitable path to start server
maybe https://github.com/mina-deploy/mina/pull/349 will be help
