### ISSUE TITLE
i deploy my project with mina and puma but cannot load gems

### ISSUE THREAD

**Issue by lanjingyu** [mina-deploy/mina#351]
The errors is here：
/home/xiaopeng/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- bundler/setup (LoadError)
	from /home/xiaopeng/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /home/xiaopeng/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/xiaopeng/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/xiaopeng/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/xiaopeng/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /xiaopeng/proj/blog/releases/6/config/boot.rb:3:in `<top (required)>'

I think mybe the vender/bundle thing. i saw bundle folder there.

**Comment by gabskoro** [comment]
I suppose that's the first time that you're deploying with this ruby version, just ssh to your server and type in
```
gem install bundler
```

**Comment by gabskoro** [comment]
Ooh, already fixed :)
