### ISSUE TITLE
git command on server is /usr/local/cpanel/3rdparty/bin/git

### ISSUE THREAD

**Issue by sharpmachine** [mina-deploy/mina#355]
To run git on my server I have to run the command: `/usr/local/cpanel/3rdparty/bin/git`.

So when I run `mina deploy` I get back `git: command not found`. 

I've set up `git` as an alias so when I'm ssh'd in I can run `git` and it works. However when using Mina it doesn't. How can I Mina to work for me?

Thanks.

**Comment by heliohead** [comment]
Make a symbolic link point /usr/local/cpanel/3rdparty/bin/git to /usr/local/bin if you have a root access.

Probaly will work

**Comment by d4be4st** [comment]
you need to install git on your server

**Comment by lupetalo** [comment]
`ln -sfv /usr/local/cpanel/3rdparty/bin/git git`
Does not work...
it outputs:
``git' -> `/usr/local/cpanel/3rdparty/bin/git'`
but i can execute `/usr/local/cpanel/3rdparty/bin/git` but i can't only `git`

**Comment by phgeek** [comment]
To add _3rdparty/bin_ to PATH variable run:
`$ export PATH=$PATH:/usr/local/cpanel/3rdparty/bin`

In order to make it permanent adds this line to _.bash_profile_
`$ echo export PATH=$PATH:/usr/local/cpanel/3rdparty/bin >> ~/.bash_profile`

Now you can run just `$ git`
