### ISSUE TITLE
Unicorn server will not restart

### ISSUE THREAD

**Issue by pjjarrar** [mina-deploy/mina#358]
I know the issue, i just don't know how to solve it. I'm using digital ocean as a host provider, and Unicorn is pointing to a different directory. How do i get it to point to my application?

 * Restarting Unicorn web server unicorn                                                                              /usr/local/rvm/gems/ruby-2.2.1/gems/unicorn-4.9.0/lib/unicorn/configurator.rb:543:in `chdir': No such file or directory @ dir_chdir - /home/rails/rails_project (Errno::ENOENT)
	from /usr/local/rvm/gems/ruby-2.2.1/gems/unicorn-4.9.0/lib/unicorn/configurator.rb:543:in `working_directory'
	from /etc/unicorn.conf:4:in `reload'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/unicorn-4.9.0/lib/unicorn/configurator.rb:75:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/unicorn-4.9.0/lib/unicorn/configurator.rb:75:in `reload'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/unicorn-4.9.0/lib/unicorn/configurator.rb:68:in `initialize'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:100:in `new'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:100:in `initialize'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/unicorn-4.9.0/bin/unicorn:126:in `new'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/unicorn:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.1/bin/unicorn:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'
master failed to start, check stderr log for details

**Comment by d4be4st** [comment]
mina does not have integration for unicorn by default. please revert to the plugin for unicorn you are using.
