### ISSUE TITLE
Mina isn't compatible with non POSIX shells

### ISSUE THREAD

**Issue by dymk** [mina-deploy/mina#363]
I use fish shell, and unsurprisingly, mina does not work with that. Would there be a way to explicitly configure a shell to use, e.g. when a setting like `set :shell "bash"` is present, have mina wrap commands with `bash -c <command>`?

**Comment by d4be4st** [comment]
I will accept your PR for different shells.

for mina 1.0.0 you can set a different deploy script to use with `set :deploy_script, "your_deploy_script.rb`
