### ISSUE TITLE
Asset precompilation when changes only occur in included gems

### ISSUE THREAD

**Issue by Epigene** [mina-deploy/mina#369]
It seems that mina does not detect asset changes and therefore skips precompilation when the changes have only occured in included gems (Rails engines).

So far we solve this oversight by forcing precompilation selectively with a check in deploy block

```ruby
deploy do
  if hash.extras.include?("compile")
    invoke :'rails:assets_precompile:force'
  else
    invoke :'rails:assets_precompile'
  end
end
```

And running

```
mina deploy[compile]
```

Is there any configuration to be done to expose mina to asset changes in gems or is this a feature yet to be developed?

**Comment by flowerett** [comment]
If I understand you right, you need to pass some settings to the deploy section.

but you always could do it in a regular way:
```ruby
set :force_precompile, -> { true }
```

and use this setting later as you describe above, like:
```ruby
deploy do
  if force_precompile
    invoke :'rails:assets_precompile:force'
  else
    invoke :'rails:assets_precompile'
  end
end
```
Does it makes sense?

**Comment by Epigene** [comment]
Codewise - no. No need for the set directive, as `hash.extras` contains "compile".
Functionality-wise, yes. Normally we do standard `mina deploy` that does the "smart" precompile when asset changes are detected. Unfortunately it seems this detection does not work for assets in gems.

**Comment by d4be4st** [comment]
you can use env variables to force asset pecompilations

`mina deploy force_assets=true`

**Comment by MarceloCajueiro** [comment]
Just a heads up that the right env variable is: `force_asset_precompile=true`
