### ISSUE TITLE
Failed with status 1 (4864) since version 0.3.7

### ISSUE THREAD

**Issue by matheusvetor** [mina-deploy/mina#370]
Hello, when i try to use mina in version up 0.3.4 i get the following error:

```
-----> DB migrations unchanged; skipping DB migration
-----> Skipping asset precompilation
cp: ‘/path/current/public/assets/.’ and ‘/path/./tmp/build-145485975217980/public/assets/.’ are the same file
! ERROR: Deploy failed.
-----> Cleaning up build
Unlinking current
OK
Connection to [ip] closed.

 !     Command failed.
       Failed with status 1 (4864)
```

My Gemfile:

```
source 'https://rubygems.org'

gem 'rails', '4.2.5.1'
gem 'rails-i18n'

gem 'web-console', '~> 2.0'
gem 'sass-rails', '~> 5.0'
gem 'compass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'mysql2', '~> 0.3.18'

gem 'devise'
gem 'devise-i18n'

gem 'cancancan', '~> 1.10'

gem 'simple_form', '3.2.1'

gem 'carrierwave'

gem 'friendly_id'

gem 'mini_magick'

gem 'will_paginate', '3.1.0'

gem 'ckeditor'

gem 'newrelic_rpm'

gem 'inherited_resources'

gem 'slim'

gem 'bootstrap-sass', '3.3.6'
gem 'momentjs-rails', '>= 2.8.1'
gem 'bootstrap3-datetimepicker-rails'
gem 'font-awesome-rails'
gem 'fancybox2-rails', '~> 0.2.8'
gem 'bxslider-rails'
gem 'nav_lynx'
gem 'plupload-rails'
gem 'html5shiv-rails'
gem 'cocoon'
gem 'select2-rails'
gem 'stringify_date', '0.0.5'
gem 'respond-js-rails'
gem 'modernizr-rails'
gem 'owlcarousel-rails'

gem 'enum_help'

gem 'carrierwave-video'
gem 'carrierwave-video-thumbnailer'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'mina', '0.3.4'
  gem 'dedent'
  gem 'spring'
end

gem 'impressionist'
gem 'rambulance'

gem 'ransack', '1.6.4'

```

The SO is Ubuntu Server 14.04.3

**Comment by GosuSheep** [comment]
I am not sure if they will help your issue, but I received the same error when I precompiled assets manually. After checking in a change to an asset so Mina would precompile, the deploy succeeded.

**Comment by SLSLogic** [comment]
is 'public' or 'public/assets' in your shared_paths? If so, that's the problem. mina copies current/public/assets to $build_path/public/assets when it skips asset precompilation

**Comment by holysoros** [comment]
@SLSLogic But mina will completely compile all assets if 'public/assets' is not in shared_paths, even though there is a very little css change.

**Comment by Akram-Khan** [comment]
I am getting this error at the time of precompilation, mina fails to precompile assets and fails. 
[
I, [2016-05-26T09:55:52.264527 #29407]  INFO -- : Writing /home/asd/tmp/build-14642709215400/public/assets/active_admin-ba378a58bccb651f7cfb57c3ff37c223c93969809b364215c43cc1b0ca613791.js.gz
bash: line 225: 29407 Killed                  RAILS_ENV="production" bundle exec rake assets:precompile RAILS_GROUPS=assets
! ERROR: Deploy failed.
-----> Cleaning up build
Unlinking current
OK
Connection to ip closed.

 !     Command failed.
       Failed with status 1 (4864)](url)

**Comment by d4be4st** [comment]
@matheusvetor you precompiled your assets manually and commited it to git version. If you want to do that manualy just comment out `invoke rails:assets_precompile` in deploy task

@Akram-Khan it looks like your assets are faulty. have you tried compiling it manually?

**Comment by TheBrockEllis** [comment]
I ran into this same issue and couldn't find any good answers. Finally figured out that it was my Digital Ocean droplet running out of RAM and the process was being killed. You can read more about my solution [here](http://thebrockellis.com/2017/01/10/Mina-being-killed-by-bash).
