### ISSUE TITLE
Mina Operation timed out 65280

### ISSUE THREAD

**Issue by dcalixto** [mina-deploy/mina#373]
i'm trying to use mina to deploy on a ec2 instance. i setup and configured everything. but mina continue to show:

ssh: connect to host website.com port 22: Operation timed out

! Command failed. Failed with status 1 (65280)
some is having the same issue with mina?

**Comment by alfie-max** [comment]
@dcalixto  I hope when you said `website.com` it isn't literally the same.

**Comment by d4be4st** [comment]
Your server is not setup correctly.
