### ISSUE TITLE
How to invoke the script as bash even the default shell on server is fishshell?

### ISSUE THREAD

**Issue by chengguangnan** [mina-deploy/mina#374]
I noticed that do `mina setup --simulate`, it prints a shebang using bash `#!/usr/bin/env bash`.

However, running `mina setup` would run the script with default shell on sever, which is fish-shell is my case.

Is there a way for mina to switch to bash when executing the command? 

```
       Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
       fish: echo "-----> Setting up /u/apps/" && (
       ^

 !     Command failed.
       Failed with status 1 (127)

```

**Comment by d4be4st** [comment]
Mina can't change this. Mina uses your ssh user and runs a script on the server. You need to change your default shell for deploy user to use bash instead of fish-shell

http://serverfault.com/questions/106722/choosing-the-shell-that-ssh-uses
