### ISSUE TITLE
Is there a good way to tag deployed git sha with the current release version?

### ISSUE THREAD

**Issue by twe4ked** [mina-deploy/mina#378]
Title. Thanks.

**Comment by devvmh** [comment]
I think the best way would be this:

1. `mina deploy --simulate > script.sh`
2. Take a look at the script, and decide where you want your command to go.
3. Figure out how to do what you want in a shell command, for instance, it might be something like `VERSION=$(cat version.txt) git tag -a -m "$VERSION" HEAD; git push --tags`
4. add a line in the appropriate spot to config/deploy.rb saying `queue %( VERSION=$(cat version.txt) git tag -a -m "$VERSION" HEAD; git push --tags )`

Wouldn't that solve the problem?

**Comment by d4be4st** [comment]
@twe4ked current sha is saved in `#{deploy_to}/scm/FETCH_HEAD`

we use this little command in :launch 

`cut -c-10 #{deploy_to}/scm/FETCH_HEAD > #{deploy_to}/#{current_path}/public/version.txt`

**Comment by twe4ked** [comment]
Thanks @devvmh and @d4be4st!
