### ISSUE TITLE
RVM not found

### ISSUE THREAD

**Issue by solisoft** [mina-deploy/mina#379]
Hi All,

I have a little issue while trying to do a mina setup

soligest [master●] % mina setup --verbose

-----> Using RVM environment 'ruby-2.2.4@soligest'
       $ rvm use "ruby-2.2.4@soligest" --create
       sh: ligne 9: rvm : command not found

 !     Command failed.
       Failed with status 1 (1)

Here my rvm info

rails@ns3365723:~$ rvm info

system:

  system:
    uname:       "Linux ns3365723.ip-37-187-77.eu 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux"
    system:      "ubuntu/14.04/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)"
    zsh:         " => not installed"

  rvm:
    version:      "rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "8 days 4 hours 41 minutes 24 seconds ago"
    path:         "/home/rails/.rvm"

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         ""
    irb:          ""
    gem:          ""
    rake:         ""

  environment:
    PATH:         "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/rails/.rvm/bin:/home/rails/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

What's wrong? 

I'm running ubuntu 14.04

**Comment by alfie-max** [comment]
@solisoft Could you make sure that `require 'mina/rvm'` is uncommented in your `deploy.rb`

This is the only thing i could think of causing this issue. If this doesn't fix it. Please do report back with your complete `deploy.rb` in a gist or something.

**Comment by solisoft** [comment]
I don't remember how I did figure out my problem, but I remember that it wasn't a mina issue ... so I close this comme ;)
