### ISSUE TITLE
Repository not found, Multiple github deploy keys for a single user on a single server

### ISSUE THREAD

**Issue by evenluo** [mina-deploy/mina#382]
Hi guys,
mina is great! And I used it to deploy one backend last month.
And recently I was trying to deploy multiple apps on a single server. And I have this problem.

I setup the git config via this guide : [USING MULTIPLE GITHUB DEPLOY KEYS FOR A SINGLE USER ON A SINGLE LINUX SERVER](http://snipe.net/2013/04/multiple-github-deploy-keys-single-server/).  I did pulled from github manually. And It's work

Now I use mina try to deploy my app. It came into this:

```
-----> Using RVM environment 'ruby-2.3.0@default'
Using /home/deploy/.rvm/gems/ruby-2.3.0
-----> Creating a temporary build path
-----> Cloning the Git repository
Cloning into bare repository '/var/www/apollo/scm'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
! ERROR: Deploy failed.
-----> Cleaning up build
Unlinking current
OK
Connection to *.*.*.* closed.

 !     Command failed.
       Failed with status 1 (4864)
```

Any solutions ? thx!

**Comment by AlfredoRoca** [comment]
I'm using ssh agent forwarding in Mina config to use my local SSH key, the same to connect to my remote server:
set :forward_agent, true     # SSH forward_agent.
Check the convenience to enable ssh agent. 2 good articles at http://unix.stackexchange.com/a/90869 & http://rabexc.org/posts/pitfalls-of-ssh-agents.

**Comment by evenluo** [comment]
@AlfredoRoca you are right, Thank you very much.
