### ISSUE TITLE
/bin/bash: Argument list too long

### ISSUE THREAD

**Issue by frankh** [mina-deploy/mina#383]
I'm trying to convert a large capistrano project to mina

When I try to run it I'm now getting this error

```
       /bin/bash: Argument list too long

 !     Command failed.
       Failed with status 1 (1)
```

Do I need to manually break up commands in some way?

**Comment by alfie-max** [comment]
@frankh What exactly did you run, and could you please include the complete error log.

**Comment by d4be4st** [comment]
@frankh this seems like a bash issue. But i believe breaking the commands up will fix the issue
