### ISSUE TITLE
Unaccessible variable

### ISSUE THREAD

**Issue by thiagogsr** [mina-deploy/mina#385]
My deploy is configured to staging and production.
```
/config/deploy.rb
/config/deploy/staging.rb
/config/deploy/production.rb
```
After update from 0.3.7 to 0.3.8 my environment files can't access the `deploy.rb` variables, eg: `application`. So I had duplicate these required variables.

**Comment by alfie-max** [comment]
@thiagogsr Could this be some other issue? I'm using 0.3.8 and couldn't reproduce the issue.

**Comment by d4be4st** [comment]
Mina does not have multiple staging functionality by default.
