### ISSUE TITLE
Shared paths does not get updates after deploy

### ISSUE THREAD

**Issue by sintro** [mina-deploy/mina#388]
Is it normal behavior of mina to not perform the automatic updates of file structure, presented in shared_paths, after mina deploy?
I can assume, that for some directories there are no reason to touch the files after deployment at all (for example, no reasons to update logs). But there are cases, when you can change some folder on local machine, and want to move this folder in mina`s remote structure out from 'releases' to 'shared'. In my case, I have 'backup' folder with configuration files of Backup gem, and I don`t want it to be in releases. Is there any way to do automatic updating of this shared folder?

**Comment by d4be4st** [comment]
shared_paths are only simlinked. it works only if they are in your version controll.

Atomatically no, you would have to `scp` it yourself in `on :before` hook.

**Comment by alfie-max** [comment]
@sintro I believe this is not an issue. Could you please close it out.
