### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by solisoft** [mina-deploy/mina#391]
Hi All,

I'm trying to figure out why my mina deploy is not working anymore ... 
-----> Creating a temporary build path
       Host key verification failed.
 !     ERROR: Deploy failed.
-----> Cleaning up build
       Unlinking current
       OK

I can access my server using mina ssh
and from my ssh console I can clone my repository ... what's wrong then ?

Thank you for your help

**Comment by solisoft** [comment]
Found my issue ...

**Comment by Nekromancer** [comment]
Can you elaborate on that?
