### ISSUE TITLE
Incompatibility with zsh?

### ISSUE THREAD

**Issue by samuelpismel** [mina-deploy/mina#395]
I'm using zsh with oh-my-zsh and rvm on global instalation as root.

After editing the deploy.rb and uncommented the rvm settings, I ran `mina deploy` and got this error:
```
zsh:83: command not found: bundle
```
I've moved my rvm.sh from /etc/profile.d/ to /root and added a `source /root/rvm.sh` on the top of my **.zshrc**  to follow the #320 tip but I still get the error...  

What can I do?

**Comment by d4be4st** [comment]
You need to install bundler on your server. `gem install bundler`

**Comment by samuelpismel** [comment]
But I have bundler installed on my server :/

**Comment by hendricius** [comment]
Having the same issue. Manually setting up my $PATH did the trick.

```
task :setup do
  command %{ export PATH="$HOME/.rbenv/bin:$PATH" }
  command %{ eval "$(rbenv init)" }
  command %{rbenv rehash}
  command %{rbenv install 2.2.2}
end
```

**Comment by d4be4st** [comment]
https://github.com/mina-deploy/mina/blob/master/docs/faq.md#--ruby-version-not-found-but-is-already-installed
