### ISSUE TITLE
foreman stop mina create current folder issue

### ISSUE THREAD

**Issue by dcalixto** [mina-deploy/mina#396]
Someone know why the mina can't create the current diretory after add foreman?

> -----> Cleaning up old releases (keeping 5)
> -----> Exporting foreman procfile for 
> bash: line 152: cd: /home/ubuntu/test/current: 
> File or directory not found
> sudo: bundle: command not found
> ! ERROR: Deploy failed.
> -----> Cleaning up build
> Unlinking current
> OK
> Connection to 55.77.221.43 closed.

 ```
deploy do
    # Put things that will set up an empty directory into a fully set-up
    # instance of your project.
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'
    invoke :'bundle:install'
    invoke :'rails:db_migrate'
    invoke :'rails:assets_precompile'
    invoke :'deploy:cleanup'
    invoke :'foreman:export'


    to :launch do
      queue "mkdir -p #{deploy_to}/#{current_path}/tmp/"
      queue "touch #{deploy_to}/#{current_path}/tmp/restart.txt"
      invoke 'foreman:restart'
    end
```

**Comment by inyerade** [comment]
@dcalixto how you solve this?
I have this problems with sidekiq and puma

This do not work

        ....
        on :launch do
            in_path(fetch(:current_path)) do
                command %{mkdir -p tmp/}
                command %{touch tmp/restart.txt}
            end
            invoke :'sidekiq:restart'
            invoke :'puma:phased_restart'
        end

I get 

    bash: line 197: bundle: command not found

And this work

        ...
        invoke :'sidekiq:restart'
        invoke :'puma:phased_restart'
        on :launch do
            in_path(fetch(:current_path)) do
                command %{mkdir -p tmp/}
                command %{touch tmp/restart.txt}
            end    
        end

I get 

    ...
    -----> Stop sidekiq
       Sidekiq shut down gracefully.
       .../tmp/build-15016067113095
    -----> Start sidekiq
       .../tmp/build-15016067113095
    -----> Restart Puma -- phased...
       Command phased-restart sent success
