### ISSUE TITLE
sudo: bundle: command not found

### ISSUE THREAD

**Issue by dcalixto** [mina-deploy/mina#397]
**someone is having bundle: command not found issue?**

> -----> Loading environment
> -----> Loading rbenv
> -----> Creating a temporary build path
> -----> Exporting foreman procfile for 
> sudo: bundle: command not found
> ! ERROR: Deploy failed.
> -----> Cleaning up build
> Unlinking current
> OK

**Comment by d4be4st** [comment]
@dcalixto you need to install bundler on your server

`gem install bundler`

**Comment by dcalixto** [comment]
thank you very much i solved this issue. but now i would like to know how to give access to mina/rbenv export the foreman procfile
