### ISSUE TITLE
LoadError: cannot load such file -- mina/bundler

### ISSUE THREAD

**Issue by jeffrey410469** [mina-deploy/mina#404]
After I upgraded from 0.3.8 to 1.0.0 beta,
I ran into LoadError with mina command as below:

`mina aborted!
LoadError: cannot load such file -- mina/bundler
/Users/User/Documents/personal_rails/weschool_web/config/deploy.rb:1:in '<top (required)>'
/Users/User/.rbenv/versions/2.3.0/bin/mina:23:in 'load'
/Users/User/.rbenv/versions/2.3.0/bin/mina:23:in '<main>'
LoadError: cannot load such file -- mina/bundler
/Users/User/Documents/personal_rails/weschool_web/config/deploy.rb:1:in '<top (required)>'
/Users/User/.rbenv/versions/2.3.0/bin/mina:23:in 'load'
/Users/User/.rbenv/versions/2.3.0/bin/mina:23:in '<main>'`

I found all tasks need to be required are causing LoadError.

**Comment by d4be4st** [comment]
Thank you, found out the bug

Fixed on master brach.

**Comment by hieuhlc** [comment]
@d4be4st Is this bug really fixed because i'm using mina-1.0.0.beta1 and it's exactly the same.
`LoadError: cannot load such file -- mina/bundler`

**Comment by d4be4st** [comment]
We have released beta2. Please try that
