### ISSUE TITLE
1.0.0.beta1 requires 'pry' but it's a development dependency

### ISSUE THREAD

**Issue by bianjp** [mina-deploy/mina#405]
I tried to use mina 1.0.0.beta1 in a Rails 4.2.7 project, but `bundle exec mina init` failed with:

```
bundler: failed to load command: mina (/home/vanitas/.gem/ruby/2.3/bin/mina)
LoadError: cannot load such file -- pry
    /home/vanitas/.gem/ruby/2.3/gems/mina-1.0.0.beta1/lib/mina.rb:4:in `require'
```

According to [mina.gemspec](https://github.com/mina-deploy/mina/blob/v1.0.0.beta1/mina.gemspec#L27), `pry` is a development dependency, but it is required in `lib/mina.rb`.

If I add `pry` to my `Gemfile`, `bundle exec mina init` will report another error: 

```
mina aborted!
LoadError: cannot load such file -- mina/install
    /home/vanitas/.gem/ruby/2.3/gems/mina-1.0.0.beta1/lib/Minafile:3:in `require'
```

It seems that this bug has been fixed in master branch.

But the master branch does not work now, it will report some other errors.

Hopes a working beta release coming soon.

After all, mina is an excellent tool for simple deployment. Thanks for your hard work!

**Comment by d4be4st** [comment]
Thx for the catch.

The fix is on master branch, still haven't released beta2.

Please use mina directly from github as beta1 is broken.

**Comment by bianjp** [comment]
Thanks, but the master branch does not work at the present:

```
mina aborted!
NoMethodError: undefined method `print_str' for main:Object
Did you mean?  print
    /home/vanitas/.gem/ruby/2.3/bundler/gems/mina-835e6529dc73/tasks/mina/install.rb:16:in `block in <top (required)>'
```

**Comment by d4be4st** [comment]
Nice catch. 
This is a bug with printing in `init` task. But `deploy.rb` file shoudve created

**Comment by bbnnt** [comment]
seem that the dependencies are not loaded; getting `LoadError: cannot load such file -- mina/bundler`

**Comment by hieuhlc** [comment]
I faced @bbnnt bug too. When will this be fixed?

**Comment by d4be4st** [comment]
we have released beta2. Please use that

**Comment by hieuhlc** [comment]
@d4be4st version 1.0.0.beta1 is required when install `mina-npm`. I don't install it on purpose 😄

**Comment by d4be4st** [comment]
Updated gempec for mina-npm, you should be able to use beta2 now

**Comment by bianjp** [comment]
Reproduced in `master` branch. 
And since 1.0.0.beta2 has #407 , there isn't any working version for 1.0 now.

Any way to require `pry` only when developing this gem?

1.0.0.beta1 and 1.0.0.beta2 both have severe bugs and are not working properly. Maybe it is caused by the lack of test? Currently I may not be able to contribute code to `mina`, but I would be pleased to test it. If you need, you can tell me to test before publishing a new release.
