### ISSUE TITLE
Undefined method queue with mina v1.0.0-beta2

### ISSUE THREAD

**Issue by glazzara** [mina-deploy/mina#408]
Hi,

I am using Rails 5 and Ruby 2.3.1p112 with mina v1.0.0-beta2.
I have the following error while running `mina deploy` :
`NoMethodError: undefined method `queue' for main:Object`

Indeed, I am using `queue` function in deploy.rb to run some commands.
Does anyone have the same problem ?

Thanks !

**Comment by d4be4st** [comment]
https://github.com/mina-deploy/mina/blob/master/docs/migrating.md

**Comment by nathanvda** [comment]
Thanks! The documentation site is still the old notation. From what I can see https://github.com/mina-deploy/mina-docs is no longer maintained? 

In other words: if I create a PR with fixes, would somebody be interested and be able to merge that (if it is ok?).
