### ISSUE TITLE
Mina doesn't enclose commands in parenthesis.

### ISSUE THREAD

**Issue by x-yuri** [mina-deploy/mina#417]
`config/deploy.rb`:
```ruby
...
  deploy do
    ...
    invoke :'npm:install'
    command 'npm run build:prod'
  end
...
```

```bash
$ bundle exec mina deploy
...
    rm -rf .git &&
    
          echo "-----> Installing node modules using Npm"
          sub_directory=$(pwd | sed -r "s/.*?$(basename $build_path)//g")
          mkdir -p "/home/u1/app//home/u1/app/shared/$sub_directory/node_modules"
          ln -s "/home/u1/app//home/u1/app/shared/$sub_directory/node_modules" "node_modules"
          npm install --production
         &&   # <--- syntax error here!!!
    npm run build:prod
...
```

Most likely, `mina` should enclose each command in parenthesis, probably [here][1].

[1]: https://github.com/mina-deploy/mina/blob/v1.0.0.beta2/lib/mina/commands.rb#L17

**Comment by d4be4st** [comment]
This is a bug in mina-npm plugin.

It has a bad taks configuration: https://github.com/mina-deploy/mina-npm/blob/master/lib/mina/npm/tasks.rb#L13

it writes everyting in one string without && or parenthesis.

**Comment by x-yuri** [comment]
When I do this:

```ruby
command '
  (
    echo 1
    echo 2
  )
'
command 'exit 1'
```

I get:

```bash
          (
            echo 1
            echo 2
          )
         &&
    exit 1 &&
```

Which has wrong syntax.

Also, why not automatically add parenthesis?

**Comment by d4be4st** [comment]
fixed with https://github.com/mina-deploy/mina/pull/427
