### ISSUE TITLE
How do I prevent mina from removing images uploaded on production server?

### ISSUE THREAD

**Issue by saroar** [mina-deploy/mina#419]
here is my new config but its done not work it give me error 
We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

here is my code 

``` set :shared_paths,  %w[ config/database.yml config/secrets.yml log tmp config/application.yml shared/public/files  shared/public/system shared/public/uploads ] ```

```   queue! %[mkdir -p "#{deploy_to}/shared/public/file"]
  queue! %[chmod g+rx,u+rwx "#{deploy_to}/shared/public/file"]

  queue! %[mkdir -p "#{deploy_to}/shared/public/system"]
  queue! %[chmod g+rx,u+rwx "#{deploy_to}/shared/public/system"]

  queue! %[mkdir -p "#{deploy_to}/shared/public/uploads"]
  queue! %[chmod g+rx,u+rwx "#{deploy_to}/shared/public/uploads"]

  queue! %[mkdir -p "#{deploy_to}/shared/public/private"]
  queue! %[chmod g+rx,u+rwx "#{deploy_to}/shared/public/private"] ```

**Comment by saroar** [comment]
now its duplicate images after upload here is pwd
1. http://prntscr.com/c8b5j9
2. http://prntscr.com/c8b5vh

**Comment by d4be4st** [comment]
remove `shared/` from `:shared_paths`

```
set :shared_paths, %w[  shared/public/files ]
```

links #{deploy_path}/current/shared/public/files -> #{deploy_path}/shared/shared/public/files
