### ISSUE TITLE
Mina beta2 bugs with mina-unicorn

### ISSUE THREAD

**Issue by hieuhlc** [mina-deploy/mina#420]
This bug did not happened in version 0.3

`NoMethodError: undefined method 'set_default' for main:Object`
`LoadError: cannot load such file -- mina/unicorn`

<img width="521" alt="screen shot 2016-08-22 at 21 56 02" src="https://cloud.githubusercontent.com/assets/4828178/17859327/59be4b8e-68b3-11e6-9af6-214e54db18a4.png">

**Comment by d4be4st** [comment]
mina-unicorn has is not updated to version 1.0.0

mina 1.0.0 introduced breaking chagnes
