### ISSUE TITLE
asset precompilation is sometimes significantly slower than 0.3.x

### ISSUE THREAD

**Issue by devvmh** [mina-deploy/mina#426]
I'm not sure why this is, but total deploy times seem to have gone up in mina 1.x

For a quick deploy with a small fix, 1.x is definitely faster, especially if just one file needs recompiling. Before, a small asset fix would take around 200 seconds to deploy because of asset precompilation.

However, we have a number of staging environments for our different developers, so it's not uncommon to deploy the master branch to a staging environment that hasn't been updated in a week or two. That can mean that maybe 40 asset files have changes. I just did a deploy like this, and it took 481 seconds. That means that compiling those 40 asset files takes longer than compiling all of the asset files in my current setup (I have 1285 files in the assets directory, most of which are currently getting compiled when I deploy with mina 0.3.x).

From what I can tell, it looks like each individual asset file compilation is taking significantly longer. I've had a hunch for a while that maybe this is because it's reloading the rails stack for each file? But maybe I'm wrong.

I haven't done extensive testing on this yet, so it's possible it's a rails problem and not a mina one. But I figure it's important to raise here, because if possible we should emulate the 0.3.x behaviour if it can be faster than the current 1.x behaviour in certain situations.

**Comment by devvmh** [comment]
OK here's some timing using a copy of my app

1. initial deploy, including gems/db migrations/assets (most of the time was assets), but not git cloning: 750.23s
2. Add one text file, deploy 24.97s
3. Change one javascript file (causing a recompile of about half of our JS): 59.18s
4. Change one image file 30.23s
5. Change the javascript file back to original contents: 30.13s

For comparison, here's what I had using 0.3.8 to deploy (with all assets precompiling taking the most time). Note that this has been significantly faster since using sprockets 3:

1. Initial deploy: 361.92s
2. Add one text file: 32.68s
3. Change one js file (recompile all assets): 77.87s (note that this probably uses sprockets cache)
4. Remove the text file: 29.67s

So the results are definitely mixed. I'm noticing an overall improvement, except for in the initial deploys. I am suspecting that the sprockets cache is not being used to its full potential in the new setup.

**Comment by devvmh** [comment]
Some recent deploys, particularly those that update our large application.js file, have been taking up to 150s, which is singnificantly longer than mina 0.3.8's 77.87s. I'm thinking again that something has regressed (at least speed-wise).

**Comment by d4be4st** [comment]
both minas do diff on app/assets/* and vendor/assets*. The flags of the diff are slightly different but that shouldn't increase the time. 

If the diff returns false 0.3.8 copied the whole public/assets path from previous release folder.  The 1.0.0 skips everything as public/assets folder is symlinked by default.

If the diff returns true 0.3.8 did a whole assets:precomplie on an empty public/assets folder. Meaning it precomplie every single file if one line changed in application.js
1.0.0 symlinks public/assets and tmp/cache by default. In theory that should reduce the time the precomple takes place as assets:precompile will see that it has all the file in cache and will precomplie only the file that had the change.

Either way, both mina does a diff and calls assets:precomple. If it is slower that means assets:precompile is slower :(

**Comment by devvmh** [comment]
Hmm, that does match my current mental model of how it works, but something is off and taking longer. I'll keep trying to isolate it.

It definitely seems like each individual asset is taking longer to compile though. That may be because before I recompiled images every time and they were very fast, and now I'm generally just compiling JS, which takes a long time because of all the require directives.

**Comment by NazarK** [comment]
In my case it appeared that "bootsnap" was what really was slowing down everything (for 2 minutes on every deploy).

**Comment by tomkra** [comment]
I agree with @NazarK. Firstly I thought that problem is with newer version of mina but problem relied in cached files of bootsnap gem. This answer https://github.com/puma/puma/issues/1717#issuecomment-493920798 , helped me solve slow deploy issue. 

Basically once in while delete all files which name starts with bootsnap in /tmp/cache/bootsnap* on your server. After clearing these files (in my case once a week in rake task) the deploy taking same time as on `mina 0.3.x`.

**Comment by lovro-bikic** [comment]
I'll close this issue since there haven't been other complaints about Mina performance, and bootsnap seems to be a likelier suspect (I too had issues with performance until I found out that bootsnap cache [must be purged once in a while](https://github.com/Shopify/bootsnap#usage)). Feel free to reopen the issue if you get new info!
