### ISSUE TITLE
run `mina deploy` failed,because of activesupport

### ISSUE THREAD

**Issue by Drshu** [mina-deploy/mina#429]
When I run `mina deploy` always failed.  

> bundling.Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
An error occurred while installing activesupport (5.0.0), and Bundler cannot
continue.
Make sure that `gem install activesupport -v '5.0.0'` succeeds before bundling.`    

```
root@VM-79-59-ubuntu:~# gem list

*** LOCAL GEMS ***

activesupport (5.0.0)
```

**But I already install active support 5.0.0,and my ruby version is 2.3.0  
How to fix it?Thanks**

**Comment by devvmh** [comment]
Are you using rbenv or rvm?

Probably you need to prefix some of the commands with `bundle exec`.

**Comment by d4be4st** [comment]
This is not a mina problem.

You have to setup your server corectly. https://github.com/mina-deploy/mina/blob/master/docs/faq.md
