### ISSUE TITLE
mina 1.0 not picking up rvm

### ISSUE THREAD

**Issue by bbnnt** [mina-deploy/mina#430]
Sorry if solved; but could not find a related issue

used to have this :
```
task :environment do
  invoke :'rvm:use[ruby-2.3.1]'
end
```

Following the migration guide, everything works pretty find but the above part, returning when deploying :
`Don't know how to build task 'rvm:use[ruby-2.3.1]' (see --tasks)`

I hoped that setting rvm_path would do the trick, but it does not.i don't see any version of rvm being picked up when deploying, and obviously it fails at when mina runs bundle install.  i'm stuck in this upgrade.. big thx for any help provided

**Comment by devvmh** [comment]
@bbnnt I had a similar problem and had to switch to this syntax:

    task :environment do
      invoke :'rvm:use', 'ruby-2.3.1'
    end

After that, I had another problem with the rvm_path variable I've posted over at #414. For now I'm using a patched version:

    gem 'mina', git: 'https://github.com/devvmh-forks/mina.git', branch: 'fix/rvm-path'

Here's the diff. It seems to be some problem with the specific variable name. If you don't have the same issue and don't need the fork, please post over at #414 to help me/the maintainers figure it out: https://github.com/mina-deploy/mina/compare/master...devvmh-forks:fix/rvm-path

**Comment by d4be4st** [comment]
yes, the new invoke syntax is:

`invoke :task, parameters`
