### ISSUE TITLE
Get deploy error

### ISSUE THREAD

**Issue by begin29** [mina-deploy/mina#431]
Hey there!
I faced with problem that need to specify when deploy was successful or get error.
How to check it?

**Comment by frazboyz** [comment]
Are you talking about the 'launch' block? Are you trying to run a app server in there? If so... i was running into issues when trying to launch puma but all i had to do was add 'bundle exec' infront of that.

**Comment by d4be4st** [comment]
We need more information @begin29

**Comment by d4be4st** [comment]
More than month old, closing
