### ISSUE TITLE
Restart doesn't work

### ISSUE THREAD

**Issue by jmuheim** [mina-deploy/mina#432]
I have the following deploy task:

```
desc "Deploys the current version to the server."
task deploy: :environment do
  deploy do
    # Put things that will set up an empty directory into a fully set-up
    # instance of your project.
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'
    invoke :'bundle:install'
    invoke :'rails:db_migrate'
    invoke :'rails:assets_precompile'
    invoke :'notify_rollbar'

    to :launch do
      in_path(fetch(:current_path)) do
        command %{mkdir -p tmp/}
        command %{touch tmp/restart.txt}
      end
    end
  end
end
```

Sadly, the file `tmp/restart.txt` doesn't really seem to be touched, as I have to manually touch it myself to really make Rails restart. What's wrong here?

**Comment by jmuheim** [comment]
By the way, what's the difference between `on` and `to`?

**Comment by jmuheim** [comment]
I have done it like this, now it's working:

```
desc "Deploys the current version to the server."
task deploy: :environment do
  deploy do
    # ...

    to :launch do
      invoke :restart
    end
  end
end

task :restart do
  queue %[echo '-----> Restarting Rails app']
  queue "touch #{deploy_to}/shared/tmp/restart.txt"
end
```

**Comment by cameronbourgeois** [comment]
@jmuheim I was having a similar issue recently with restarting my server. The initial issue was related to the `mina-unicorn` gem, however I did go on to discover that it seems as though the `current` symlink has not yet been linked correctly before the `:restart` task runs.

My issue is over on the `mina-unicorn` gem: https://github.com/scarfacedeb/mina-unicorn/issues/21

**Comment by devvmh** [comment]
@jmuheim `on` is the new `to`, since the 1.0.x upgrade, AFAIK. I'm using this code:

```
task deploy: :environment do
  deploy do
    # ... lots of stuff
    on :launch do
      invoke :'passenger:restart'
    end
  end
end

namespace :passenger do
  task :restart do
    in_path(fetch(:current_path)) do
      comment 'Restarting passenger'
      command %(touch tmp/restart.txt)
    end
  end
end
```

I'm not sure what's different about my code & yours, but my guess is it's on vs to, and not the use of invoke... but who knows?

**Comment by cameronbourgeois** [comment]
Hey guys, it seems I fixed my issue by also moving my restart commands into a seperate task and referencing from the `to :launch` block.

Thanks!
