### ISSUE TITLE
Change output precompiling asset color

### ISSUE THREAD

**Issue by heliohead** [mina-deploy/mina#434]
Every time i see that bunch of red lines when i deploy my code i feel bad :( 

Maybe orange :)
![screenshot 2016-09-14 21 59 13](https://cloud.githubusercontent.com/assets/675604/18534956/84370fca-7ac6-11e6-91a8-4d5a75acad2c.png)

**Comment by d4be4st** [comment]
This is a problem due to rails assets:precomplie task where that task for some reason outputs to stderr :(

maybe we can make an expeption for files starting with 'I, '

**Comment by heliohead** [comment]
💕 💞 💓 💗
