### ISSUE TITLE
Can't open rails console when doing ssh through mina

### ISSUE THREAD

**Issue by Shwetakale** [mina-deploy/mina#435]
I am using mina version ```0.3.8```. But when I do ssh with mina

    mina ssh on=staging

I am not able to open rails c

    bundle exec rails c satging
    bundler: command not found: rails
    Install missing gem executables with `bundle install`

It used to work fine with earlier version of mina i.e. 0.3.7. On same server when I do normal ssh I am able to open console and even with mina

    mina "rails[c]" on=staging

is working fine. Am I missing something in setup or issue introduced in newer version of gem?

**Comment by d4be4st** [comment]
i do not know what `on` is, but your server is not configured properly. 
Your deploy user/non-interactive shell mina uses does not have access to gems.

Plesae take a look at our FAQ. https://github.com/mina-deploy/mina/blob/master/docs/faq.md
