### ISSUE TITLE
Default tasks?

### ISSUE THREAD

**Issue by MrOutis** [mina-deploy/mina#436]
I like my deploys with sugar, that's why I gave **mina** a try.

I have a minimum setup
```ruby
# config/deploy.rb
set :user, 'deploy'
set :domain, 'myissue.com'
set :term_mode, nil

task :setup do
  queue 'echo "is this a bug?" >> issue.txt'
  queue 'echo "or is it a feature?" >> issue.txt'
end
```

When I run: `mina setup`
It requires me to set a `deploy_to` path.

```ruby
set :deploy_to, 'whatever'
```

I ran again `mina setup`.

```
-----> Setting up whatever

ls: cannot access 'whatever': No such file or directory
! ERROR: Setup failed.
! Ensure that the path 'whatever' is accessible to the SSH user.
! Try doing:
!    sudo mkdir -p "whatever" && sudo chown -R deploy "whatever"
Connection to 45.55.77.252 closed.
       Elapsed time: 21.76 seconds
```

wait, what!? I'm not requesting this!
To have a complete view, I ssh'd into my server and, indeed, mina did the job.

There's an `issue.txt` file on my home, but there's also a `whatever` directory with
a `releases` and `shared` directories inside.

If this is a feature, someone should make it clearer.
I'd love to have just my *coffee with some sugar*, not a whole *mocha-frapuccino-chai*.

```
❯ mina --version
Mina, version v0.3.8
```

I can send a pull request if the intention is the former one :smiley: .

**Comment by MrOutis** [comment]
Having pre-configured scripts is awesome, I would hate writing the same file every time I'm going to deploy a Rails application.

But I guess this could be better organized with `invoke`s ; any thoughts?

**Comment by d4be4st** [comment]
The job of the setup task is to setup your deploy_to folder with all needed folders.

**Comment by devvmh** [comment]
Just to fill in a bit better - your setup task is doing the jobs you asked in addition to mina's setup tasks.

if you want a custom task that just creates two files, you need to pick a name that isn't setup

For instance

```
namespace :custom do
  task :setup do
    queue 'echo "is this a bug?" >> issue.txt'
    queue 'echo "or is it a feature?" >> issue.txt'
  end
end
```

would do what you're looking for, and you'd just need to run `mina custom:setup` on the command line
