### ISSUE TITLE
Support for nvm

### ISSUE THREAD

**Issue by dhyegofernando** [mina-deploy/mina#440]
It would be pretty great to use mina tasks for [creationix/nvm](https://github.com/creationix/nvm) just like we do for [rvm/rvm](https://github.com/rvm/rvm)

p.s. right now, I'm using this [gist](https://gist.github.com/MichalB/d1244b876c0aaa314d1a) to do this work.

Thanks for the awesome work done here. :+1:

**Comment by d4be4st** [comment]
As we do not use nvm in house there is no incentive for us to code it.

Also we wont be adding any more modules in mina (we might event take out a few as we did with whenever and foreman) so it would be great if you or anyone else could make a 3rd party plugin for mina :)
