### ISSUE TITLE
Mina not loading prompt to ask for Git password

### ISSUE THREAD

**Issue by SimonTheLeg** [mina-deploy/mina#446]
Hi there,

when I try to run _mina deploy_ the program always "freezes" right before I am supposed to enter my Bitbucket password and does not accept any keyboard inputs...

here's the log when running in verbose

```
username@privateServer password: [_I enter my ssh password no problem_]
-----> Creating a temporary build path
       $ touch "deploy.lock"
       $ mkdir -p "$build_path"
       $ cd "$build_path"
-----> Cloning the Git repository
       $ git clone "<link to my private Bitbucket server>" "/home/rails/FSPP/scm" --bare
       Cloning into bare repository '/home/rails/FSPP/scm'...
```

But now instead of prompting me for my Bitbucket password the application just freezes and does nothing, no matter how long I wait.

Strangely enough, when I press ctrl + C the console actually outputs the following, suddenly containing the prompt for the password.. (Of course at this stage it is too late as the mina task has already been closed)

```
^C
-----> Mina: SIGINT received.
       Killed by signal 15.

       Password for 'http://simon.bein@bitbucket.fs-wi.tk:7990': 
 !     Run Error
```

I am using the standard OS X 10.12 Terminal.

**Comment by d4be4st** [comment]
Please take a look at our FAQ: https://github.com/mina-deploy/mina/blob/master/docs/faq.md#--mina-hangs-after-i-type-my-password-in
