### ISSUE TITLE
Prompts Are not displayed - or displayed after killing process

### ISSUE THREAD

**Issue by h3christophe** [mina-deploy/mina#449]
So I have an issue with mina 1.0.0
Using MacOsSierra 10.12 

Very simillar to https://github.com/mina-deploy/mina/issues/163
But their solutions did not work for me 

When I try to deploy 
```
-----> Cloning the Git repository
       Cloning into bare repository 'XXX'
```
The process is Freezing 
This is because the git clone operation requires me to enter my passphrase for the ssh key 

Unfortunately I don't get the prompt 
It is only when I force quit the process that the prompt is displayed
like so

```
-----> Creating a temporary build path
-----> Environment: staging
-----> Termode: nil
-----> Cloning the Git repository
       Cloning into bare repository 'XXXXX'...


^C      
-----> Mina: SIGINT received.
       Killed by signal 15.

       Enter passphrase for key '/root/.ssh/id_rsa_': 
 !     Run Error
````

Any Idea ? 
Thank you

**Comment by ianrtracey** [comment]
I am experiencing the same problem

**Comment by d4be4st** [comment]
please read the faq first!
