### ISSUE TITLE
going back to 0.3.8

### ISSUE THREAD

**Issue by reicheltd** [mina-deploy/mina#451]
Going from 0.3.8 to 1.0 got me just problems for over an hour. Everything was going so well. Why did I upgrade...Going back to the old version for now. The migrating Readme didnt help either.

**Comment by Nekromancer** [comment]
Is there any particular issue you want help with? I managed to do migration and i'm pretty satisfied with effects

**Comment by d4be4st** [comment]
not issue, but you are welcome to post your problems
