### ISSUE TITLE
failed to create symbolic link ‘./config/database.yml’: File exists

### ISSUE THREAD

**Issue by floydj** [mina-deploy/mina#452]
I get the above error when trying to migrate from 0.3.8 to 1.0.0.

The config/database.yml does already exist for some reason. No problems with this until I upgraded to 1.0. Any ideas on how to resolve?

**Comment by floydj** [comment]
My fault...I see I only need to link the entire config directory now.

**Comment by floydj** [comment]
Actually, I think I need to reopen this. 

If I have this in my config/deploy.rb file:

```
set :shared_dirs, fetch(:shared_dirs, []).push('log', 'output_documents', 'pdf_bundles',
                                               'files', 'public/uploads', 'public/system')
set :shared_files, fetch(:shared_files, []).push('config/database.yml',
                                                 'config/secrets.yml',
                                                 'config/central_documents.yml',
                                                 'config/paperclip_s3.yml')

```

Then I get the following:

`$ ln -s "/home/deployer/teamsite/shared/config/secrets.yml" "./config/secrets.yml"
       ln: failed to create symbolic link ‘./config/secrets.yml’: File exists`

How do I get this working the way it was under 0.3.8?

**Comment by floydj** [comment]
I'm sorry...my fault again. I accidentally had the secrets.yml in my repo. Closing again.

**Comment by ralfebert** [comment]
Stumbled upon the same problem - I think it would make sense to delete :shared_files before linking because often these files are in the repo for development and are supposed to be overwritten by the link to the shared file under mina deployment.

Workaround: Delete them in the deploy after cloning like this:

```
  deploy do
    # Put things that will set up an empty directory into a fully set-up
    # instance of your project.
    invoke :'git:clone'
    fetch(:shared_files, []).each do |linked_path|
      command %{rm -f "./#{linked_path}"}
    end
```
