### ISSUE TITLE
Changing git host

### ISSUE THREAD

**Issue by frazboyz** [mina-deploy/mina#458]
Hi, so i was migrating my repositories from github to gitlab.

After importing my repositories into gitlab and adding me ssh key etc I updated the repository variable in mina and tried to deploy and got this error.

`-----> Creating a temporary build path        
-----> Fetching new git commits        
       Host key verification failed.
       fatal: Could not read from remote repository.
       
       Please make sure you have the correct access rights
       and the repository exists.
 !     ERROR: Deploy failed.   
`

**Comment by frazboyz** [comment]
I just ended up re-setting up mina. Maybe there is an easy way to switch host?

**Comment by d4be4st** [comment]
There is no way to automatically detect repo git host change.
You need to either mannually change the host in scm/config, or delete the
contents of the scm folder.

Will add to faq.

**Comment by frazboyz** [comment]
Sounds good.
