### ISSUE TITLE
Set variables via command line is not captured in method set?

### ISSUE THREAD

**Issue by Zhomart** [mina-deploy/mina#470]
set?(:var) returns false even if :var is set in command line options, e.g.

```
$ mina deploy identity_file=id_rsa

# in config/deploy.rb
# set?(:identity_file) returns false
```

Edit:

Interestingly, fetch(:identity_file) returns "id_rsa"

**Comment by Zhomart** [comment]
My current temp. fix:

```ruby
# temp. fix for issue mina-deploy/mina#470
set :identity_file, fetch(:identity_file) if fetch(:identity_file)
set :ssh_options, fetch(:ssh_options) if fetch(:ssh_options)
```

**Comment by hendricius** [comment]
they are available via `ENV['identity_file']` hash.

**Comment by Zhomart** [comment]
I want it to be used in https://github.com/mina-deploy/mina/blob/master/lib/mina/backend/remote.rb#L27
