### ISSUE TITLE
Less obscure behaviour while copying the assets

### ISSUE THREAD

**Issue by lorenzosinisi** [mina-deploy/mina#473]
I wanted to open a pull request making the task :assets_precompile (For Rails) more explicit.

Right now if the task :assets_precompile is skipped the output says ```Skipping asset precompilation``` while what is happening is that the previous public/assets folder is copied into the new one. This is a very obscrure behaviour and outputting what is 'actually' happening will prevent confusion. What do you think?

in ```tasks/mina/rails.rb```
```
66 -   skip: %{echo "-----> Skipping asset precompilation"},
66 +   skip: %{echo "-----> Skipping asset precompilation and cloning from previous assets folder."},
```

**Comment by d4be4st** [comment]
This is the way `0.3.x` version has done.
In `1.0.0` assets are link shared and not copied.
