### ISSUE TITLE
mina deploy

### ISSUE THREAD

**Issue by bjcadvisory** [mina-deploy/mina#479]
mina deployment question
/usr/local/rvm/gems/ruby-2.2.1@igotit/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr/local/rvm in PATH, mode 042777
       usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
       [-D [bind_address:]port] [-E log_file] [-e escape_char]
       [-F configfile] [-I pkcs11] [-i identity_file]
       [-L [bind_address:]port:host:hostport] [-l login_name] [-m mac_spec]
       [-O ctl_cmd] [-o option] [-p port]
       [-Q cipher | cipher-auth | mac | kex | key]
       [-R [bind_address:]port:host:hostport] [-S ctl_path] [-W host:port]
       [-w local_tun[:remote_tun]] [user@]hostname [command]

 !     Command failed.
       Failed with status 255
mina aborted!

**Comment by d4be4st** [comment]
please add a bit of syntax highlight to your question.

But this does not look like a mina error

http://lmgtfy.com/?q=Insecure+world+writable+dir+%2Fusr%2Flocal%2Frvm+in+PATH%2C+mode+042777
