### ISSUE TITLE
WordPress current symlink

### ISSUE THREAD

**Issue by whoteaches** [mina-deploy/mina#481]
I'm deploying a bunch of WordPress websites with Mina. So simple. Love it.
I am running into a rather strange problem that I could use some expertise advise on.

The "current" symlink is updated correctly to the latest release, however, I only see the changes in the front and backend when I go into the releases folder and delete the old release folders. Strange huh?

Any idea why?

I'm posting my config below:

```
require 'mina/git'

set :user, 'lalala'
set :ssh_options, "-A"

set :domain, 'xxx.xxx.xxx.xxx'
set :deploy_to, '/var/www/xxx'
set :repository, 'xxx.git'
set :branch, 'master'

set :shared_dirs, fetch(:shared_dirs, []).push('wp-content/uploads')
set :shared_files, fetch(:shared_files, []).push('wp-config.php', '.htaccess')
task :environment do
end
task :setup do
end

desc "Deploys the current version to the server."
task :deploy do
  deploy do
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'
  end
end

```

**Comment by d4be4st** [comment]
I have not used wordpress but is there a way to restart the server?

It seems like it has all the files loaded in the memory, and when you remove old directories it figures out that it should 'restart'
