### ISSUE TITLE
mina setup or mina init, don't know how to build task

### ISSUE THREAD

**Issue by u007** [mina-deploy/mina#488]
mina setup
mina init
both returns: Don't know how to build task 'deploy' (see --tasks)

rails 5, gemfile already added mina

**Comment by lokyoung** [comment]
Could you please paste your `deploy.rb` file here?

**Comment by u007** [comment]
pls hold on,  i didnt have access to my pc 2nite, will try tomorrow night
thank you

**Comment by u007** [comment]
```
require 'mina/bundler' 
require 'mina/rails' 
require 'mina/git' 
require 'mina/rvm'

# mina
set :user, 'myuser'
set :domain, 'xyz.com'
set :deploy_to, '/home/appz/rails/production'

set :repository, 'git@bitbucket.org:xxx/appz.git'
set :branch, 'main'
task :environment do
      
  # invoke :'rbenv:load'
  invoke :'rvm:use[ruby-2.3.1-p112@default]'
  
end

set :format, :pretty
set :rvm_ruby_version, '2.3.1'

# Default value for :log_level is :debug
set :log_level, :debug
set :bundle_path, -> { release_path.join('vendor').join('bundle') }

set :linked_dirs, %w{bin log tmp/pids tmp/cache tmp/sockets vendor/bundle
    public/system public/uploads}

set :bundle_without, %w{development test james}.join(' ') 
# Default value for keep_releases is 5
set :keep_releases, 3
set :ssh_options, :compression => false, :keepalive => true

set :delayed_job_server_role, :worker
set :delayed_job_args, "-n 2"
```

**Comment by lokyoung** [comment]
@u007 Which version of mina are you using?

**Comment by u007** [comment]
1.0.3

**Comment by lokyoung** [comment]
@u007 Please follow the migrating guide https://github.com/mina-deploy/mina/blob/master/docs/migrating.md. There are some syntax in your `deploy.rb` which are unsupported in mina 1.0.3.
e.g. `invoke :'rvm:use[ruby-2.3.1-p112@default]'` should be `invoke :'rvm:use', 'ruby-2.3.1-p112@default'`.

**Comment by u007** [comment]
```bundle exec mina init
```
mina aborted!
Don't know how to build task 'init'

**Comment by d4be4st** [comment]
You can not execute init if your project is already initialized.

I have fixed this in https://github.com/mina-deploy/mina/commit/ddf823cca7c21c16e5f6ea5e566037dba19f6e92

but what does your `bundle exec mina setup` say?

**Comment by d4be4st** [comment]
Closing issue
