### ISSUE TITLE
Integrate puma and its configuration as default in mina

### ISSUE THREAD

**Issue by wonderer007** [mina-deploy/mina#493]
I wanted to integrate puma default rack server and its configurations as default with the mina gem, is this even possible? Please guide me
Thanks

**Comment by d4be4st** [comment]
Hi @wonderer007 
you can use https://github.com/untitledkingdom/mina-puma
As i can see it is upgraded to mina 1.0.0

there is also a https://github.com/hbin/mina-nginx for nginx
