### ISSUE TITLE
rails:assets_precompile from cache

### ISSUE THREAD

**Issue by zymtx5g79k** [mina-deploy/mina#494]
**mina** 1.0.6 remote: git://github.com/mina-deploy/mina.git, revision: aaf50c597223f089103cb9b0d872bd4435edefed

New deployment process start compilation from cache when I had a syntax error in specific sass file. It based on the last commit but was ignored any changes in the file.

I had removed all from `[project]/shared/cache`. After that it found my changes. It was not easy to detect.

**Comment by d4be4st** [comment]
Yes, that is the way precompilation works. 
I have added cache to shared paths because the compilation is then much faster.

This is a tradeoff we are willing to make.
