### ISSUE TITLE
Managing environment variables file application.yml 

### ISSUE THREAD

**Issue by wonderer007** [mina-deploy/mina#497]
Is there a better to way to manage your environment variable while continuous deployment using mina? Currently as suggested I have my application.yml in _/shared/config_ whenever I update my env file in location I have to manually paste those changes in production because I have ignore application.yml in .gitignore. I am looking for a solution something sending the application.yml file to the server over same **_ssh_** connection mina has established or using **_scp_** along side ssh.

Thanks in advance.

**Comment by lnikell** [comment]
@wonderer007 if you are using rvm I guess .versions.conf file fit for your purposes.
you can create .versions.conf file with all necessary env variables and have different versions of that file on local and remote machine.

**Comment by ahbou** [comment]
Since v1.0 broke the scp plugin, here's my workaround if anyone else is struggling with this.
say you have:
`set :shared_files, ['config/database.yml', 'config/application.yml']`

and right before **deploy do**
run 

```
run(:local){ 
    desc 'upload shared files' 
    fetch(:shared_files, []).each do |linked_dir|
      command "scp #{linked_dir} #{fetch(:user)}@#{fetch(:domain)}:#{fetch(:shared_path)}/#{linked_dir}"
    end
  }
```

**Comment by d4be4st** [comment]
as @ahbou wrote, use run(:local) to send your config/application.yml to a shared path

will update docs with this situation
