### ISSUE TITLE
working with rbenv/rvm etc?

### ISSUE THREAD

**Issue by ledbettj** [mina-deploy/mina#5]
Hi,

I'm trying to deploy to a server where ruby is installed using `rbenv` for the deploy user.  However, mina doesn't seem to pick it up:

```
bundle install --without development:test --path "./vendor/bundle" --binstubs bin/ --deployment
bash: line 77: bundle: command not found
```

I'm never sure which init file gets run on ssh login -- I tried adding the required `export PATH=...` statements to `.bashrc`, `.bash_profile`, and `.profile` none of which seemed to help.  I also tried setting up the `PATH` manually in the deploy task:

```
# ...
queue 'export PATH=$HOME/.rbenv/bin:$HOME/.rbenv/shims'
queue 'echo "path=$PATH"' # this doesn't include the paths above :(
invoke :'bundle:install'
# ...
```

without success (I assume each task runs in a subshell maybe?)

Any advice on how to get this setup working?

Thanks!

**Comment by born4new** [comment]
Hi there,

I just started using Mina, and I'm not using rbenv nor RVM at the moment.

I believe there has been some kind of regression here because I have the same initial problem of this thread: my bashrc is not taken into account. The export clauses fixed it aswell.

Thanks!
