### ISSUE TITLE
Provide meaningful default shared folders

### ISSUE THREAD

**Issue by jmuheim** [mina-deploy/mina#501]
I'm unsure which folders I should share. At the time being, it's the following:

    set :shared_dirs, fetch(:shared_dirs, []).push('log', 'tmp', 'public/uploads')

Maybe you should provide meaningful default shared folders? Instead of

    # set :shared_dirs, fetch(:shared_dirs, []).push('somedir')

something like

    # set :shared_dirs, fetch(:shared_dirs, []).push('log', 'tmp', 'public/uploads')

because for shared files you already do provide meaningful default ones:

    # set :shared_files, fetch(:shared_files, []).push('config/database.yml', 'config/secrets.yml')

**Comment by arun057** [comment]
should probably include `public/assets` as well

**Comment by d4be4st** [comment]
@arun057 they are included by default

Will add to documentation
