### ISSUE TITLE
Add hint about creating `shared/database.yml` in README

### ISSUE THREAD

**Issue by jmuheim** [mina-deploy/mina#503]
I followed the guide in https://github.com/mina-deploy/mina/blob/master/docs/getting_started.md step by step.

When the migration starts, and I get this:

```
-----> Migrating database
       $ RAILS_ENV="production" bundle exec rake db:migrate
       rake aborted!
       Cannot load `Rails.application.database_configuration`:
       Could not load database configuration. No such file - ["config/database.yml"]
```

Doesn't really surprise me, as I wasn't told to create one before, and the file isn't committed to git (for good reason).

When I created the file manually, it worked fine.

So maybe you should add a note about this in the getting started document?

**Comment by d4be4st** [comment]
Will update the documentation!

**Comment by sanotronics** [comment]
Hello!

I am having this exact same issue, could you please share with me what the solution is?

Thanks!
