### ISSUE TITLE
Different behavior of environment task with 0.3.8 and 1.0.6

### ISSUE THREAD

**Issue by gbgdev** [mina-deploy/mina#505]
Hi guys,

I'm using mina 0.3.8, mina-sidekiq and mina-unicorn in one of my projects.

Recently i'm trying to update mina version from 0.3.8 to 1.0.6. But after follow each step of the migration guide (https://github.com/mina-deploy/mina/blob/master/docs/migrating.md) and get the deploy task "working", i observed a different behavior with the `:environment` task.

On version 0.3.8, the `:environment` task is getting executed once, even when there are many other tasks referencing to it. On 1.0.6, its strangely getting executed twice.

The differences can be clearly observed comparing the trace log of the two versions:

**0.3.8 deploy --trace**
```
** Invoke rvm:use (first_time)
** Execute rvm:use
** Execute deploy
** Invoke sidekiq:quiet (first_time)
** Invoke environment
** Execute sidekiq:quiet
** Invoke git:clone (first_time)
** Execute git:clone
** Invoke deploy:link_shared_paths (first_time)
** Execute deploy:link_shared_paths
** Invoke configuration:link_specific_shared_path (first_time)
** Execute configuration:link_specific_shared_path
** Invoke bundle:install (first_time)
** Execute bundle:install
** Invoke configuration:sync (first_time)
** Execute configuration:sync
** Invoke rails:db_migrate (first_time)
** Execute rails:db_migrate
** Invoke rails:assets_precompile (first_time)
** Execute rails:assets_precompile
** Invoke unicorn:launch (first_time)
** Invoke environment
** Execute unicorn:launch
** Invoke sidekiq:restart (first_time)
** Execute sidekiq:restart
** Invoke sidekiq:stop (first_time)
** Invoke environment
** Execute sidekiq:stop
** Invoke sidekiq:start (first_time)
** Invoke environment
** Execute sidekiq:start
** Invoke deploy:cleanup (first_time)
** Execute deploy:cleanup
```

**1.0.6 deploy --trace**
```
** Invoke deploy (first_time)
** Execute deploy
** Invoke environment (first_time)
** Execute environment
** Invoke rvm:use (first_time)
** Execute rvm:use
** Invoke git:clone (first_time)
** Execute git:clone
** Invoke deploy:link_shared_paths (first_time)
** Execute deploy:link_shared_paths
** Invoke configuration:link_specific_shared_path (first_time)
** Execute configuration:link_specific_shared_path
** Invoke bundle:install (first_time)
** Execute bundle:install
** Invoke configuration:sync (first_time)
** Execute configuration:sync
** Invoke sidekiq:quiet (first_time)
** Execute sidekiq:quiet
** Invoke rails:db_migrate (first_time)
** Execute rails:db_migrate
** Invoke rails:assets_precompile (first_time)
** Execute rails:assets_precompile
** Invoke sidekiq:restart (first_time)
** Execute sidekiq:restart
** Invoke sidekiq:stop (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke rvm:use (first_time)
** Execute rvm:use
** Execute sidekiq:stop
** Invoke sidekiq:start (first_time)
** Invoke environment
** Execute sidekiq:start
** Invoke unicorn:launch (first_time)
** Invoke environment
** Execute unicorn:launch
** Invoke deploy:cleanup (first_time)
** Execute deploy:cleanup
```

Note on the last log that the `environment` is getting executed two times (one time on "default step" and one time on "launch step"), as if it were invoked the first time.

![image](https://cloud.githubusercontent.com/assets/8050903/21786787/e8d11f38-d6ac-11e6-8777-5420a51910ae.png)

Doing several tests I realized that any task that is explicit referred to the `environment` (example: https://cl.ly/381D0P0m3s18) makes the `environment` task get invoked and executed again.

I dont know if its a real problem, but the `rvm:use` and the other environment steps are apparently getting executed two times unnecessarily.

Do you guys also experience this behavior with the new version? Is it expected?

**Comment by d4be4st** [comment]
Will take a look! Thanks

**Comment by bdavidxyz** [comment]
Yes, I have also tasks that are randomly ran multiple times.

**Comment by d4be4st** [comment]
I think i know what the problem is

Are your tasks depending on :environment task?

```
task deploy: :environment do
...
```
?
