### ISSUE TITLE
Mina Rollback 

### ISSUE THREAD

**Issue by paulalbertdev** [mina-deploy/mina#507]
Hi ! 
I use mina v1.0.6,
and I try to rollback, unsuccessful,

I've tried : 
"mina preprod" and then "mina rollback",
"mina preprod rollback",
and "mina preprod deploy:rollback"

But it always end with a "Don't know how to build task" error

**Comment by Feuda** [comment]
@paulalbertdev 

> mina rollback

**Comment by lovro-bikic** [comment]
Hi, the task is `mina rollback`. You can check the list of tasks by running `mina --tasks`. If it doesn't appear on the list, check if `config/deploy.rb` is set up.
