### ISSUE TITLE
 Install nginx as module

### ISSUE THREAD

**Issue by dcalixto** [mina-deploy/mina#512]
I'm trying to instal nginx as a module with mina deploy but i get,

> expecting keyword_end

    ...nf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid ..

.

on modules setup.

the setup that i'm trying to instal is:

     desc "install Nginx"
        task :install do
            invoke :sudo
            queue "passenger-install-nginx-module --auto  --languages ruby,python,nodejs,meteor --nginx-source-dir=/home/ubuntu/nginx-1.9.14 --prefix=/usr --extra-configure-flags="--conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --sbin-path=/usr/sbin --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-pcre='/home/ubuntu/nginxmodule/pcre-8.37'  --with-http_gzip_static_module  --with-http_stub_status_module --without-mail_pop3_module --without-mail_smtp_module --without-mail_imap_module --with-http_gzip_static_module --without-http_autoindex_module --without-http_browser_module --without-http_fastcgi_module --without-http_geo_module --without-http_empty_gif_module --without-http_map_module --without-http_ssi_module --without-http_userid_module --user=www-data --group=www-data  --with-http_ssl_module  --add-module='/home/ubuntu/nginxmodule/openssl-1.0.1s' --add-module='/home/ubuntu/nginxmodule/nginx-rtmp-module' --add-module='/home/ubuntu/nginxmodule/headers-more-nginx-module-0.26' --add-module='/home/ubuntu/nginxmodule/ngx_pagespeed-release-1.11.33.0-beta' --add-module='/home/ubuntu/nginxmodule/nginx-push-stream-module' --add-module='/home/ubuntu/nginxmodule/ngx_http_redis-0.3.8'""
        end

someone have a idea how to setup a nginx module inside mina-deploy? thank's

**Comment by zmckenzie** [comment]
It looks like you have an extra double quote in the line. Try it with the following: 

```ruby
desc "install Nginx"
task :install do
  invoke :sudo
  queue "passenger-install-nginx-module --auto  --languages ruby,python,nodejs,meteor --nginx-source-dir=/home/ubuntu/nginx-1.9.14 --prefix=/usr --extra-configure-flags= --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --sbin-path=/usr/sbin --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-pcre='/home/ubuntu/nginxmodule/pcre-8.37'  --with-http_gzip_static_module  --with-http_stub_status_module --without-mail_pop3_module --without-mail_smtp_module --without-mail_imap_module --with-http_gzip_static_module --without-http_autoindex_module --without-http_browser_module --without-http_fastcgi_module --without-http_geo_module --without-http_empty_gif_module --without-http_map_module --without-http_ssi_module --without-http_userid_module --user=www-data --group=www-data  --with-http_ssl_module  --add-module='/home/ubuntu/nginxmodule/openssl-1.0.1s' --add-module='/home/ubuntu/nginxmodule/nginx-rtmp-module' --add-module='/home/ubuntu/nginxmodule/headers-more-nginx-module-0.26' --add-module='/home/ubuntu/nginxmodule/ngx_pagespeed-release-1.11.33.0-beta' --add-module='/home/ubuntu/nginxmodule/nginx-push-stream-module' --add-module='/home/ubuntu/nginxmodule/ngx_http_redis-0.3.8'"
end
```

At the very least this should get you past that error.

**Comment by dcalixto** [comment]
@zmckenzie  thank you very much!
