### ISSUE TITLE
`remote` command doesn't find my executable (after upgrade from 0.3 to 1.0)

### ISSUE THREAD

**Issue by jmuheim** [mina-deploy/mina#513]
I have the following custom task:

```ruby
desc "Performs a backup."
task backup: :environment do
  comment 'Performing backup'
  command %{backup perform --trigger=audit}
end
```

It gives the following error:

```
$ mina backup
-----> Performing backup
       bash: line 1: backup: command not found
       Connection to zugangfueralle01.nine.ch closed.

 !     Run Error
```

But when manually ssh'ing to the server and executing `$ backup perform --trigger=audit`, it works well.

Does `remote` miss some configuration which is loaded when ssh'ing manually?

Interestingly, this very same task worked perfectly in v0.3, but after upgrading to 1.0, it doesn't anymore

**Comment by jmuheim** [comment]
Probably better a question on StackOverflow:

http://stackoverflow.com/questions/42007271/mina-deploy-remote-command-doesnt-find-my-executable

**Comment by jmuheim** [comment]
I found a workaround, just load the env manually in the environment:

```
task :environment do
  command %{source $HOME/.bash_profile; source $HOME/.bashrc;}
end
```

But why isn't this done automatically anymore?

**Comment by d4be4st** [comment]
This is because how your bash_profile is written

There is a line on the top:

```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

which exits bash rc and does not go to the end, and i assume your program is sources at the end of your bashrc file

**Comment by jmuheim** [comment]
Just wanted to mention that it now works. I don't know, maybe a gem version update, or a change on the server side...
