### ISSUE TITLE
Does a full bundle install every time

### ISSUE THREAD

**Issue by thelucid** [mina-deploy/mina#516]
This is the case even when the gems are installed but means there are really slow deploys.

**Comment by ttp** [comment]
If it's related to mina 1.0 then just make sure you are not overriding defaults and it should work fine. Example:
```
set :shared_dirs, fetch(:shared_dirs, []) + [
  'log',
  'tmp',
  'public/system'
]
```

**Comment by anilmaurya** [comment]
@ttp I tried your solution but it didn't worked.

**Comment by d4be4st** [comment]
i would need your deploy.rb script as that shouldn't happen

also if you do `mina -d` you should have `vendor/bundle` in your `shared_dirs`
