### ISSUE TITLE
Skipping assets:precompile doesn't copy assets folder to new current_path

### ISSUE THREAD

**Issue by kidush** [mina-deploy/mina#518]
Every new deploy that I've done, when assets_precompile is called and skipped my assets has stopped work.  I've been searching on issues about it, but I cannot find out anything.

**Comment by d4be4st** [comment]
please do a `mina -d` and you should have `"public/assets"`in your `shared_dirs` variable as assets should be shared among deploys

**Comment by kidush** [comment]
Hello @d4be4st 

thanks man, I've done it and works perfectly, I'll close this issue  😄 .
