### ISSUE TITLE
Fix 'No Rakefile found' for rails:{db_create, db_migrate, db_rollback, assetts_precompile} commands

### ISSUE THREAD

**Issue by ianheggie** [mina-deploy/mina#524]
I like the gem, but there are rails:* commands that fail when run alone, eg:

      $ mina rails:db_create
      -----> Creating database
             rake aborted!
             No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
       
             Connection to licapture.timelapse.com.au closed.

             (See full trace by running task with --trace)
       !     Run Error

I will submit a PR

**Comment by d4be4st** [comment]
Answer in https://github.com/mina-deploy/mina/pull/525#issuecomment-329707654

Will add to documentation.
If you feel there is a need to create separate mina tasks for this, go ahead.
