### ISSUE TITLE
SSH to GitLab repository problem

### ISSUE THREAD

**Issue by hiepph** [mina-deploy/mina#533]
In `config/deploy.rb` I set config of repository to GitLab:

```
set :repository, 'git@gitlab.com:my_organization/my_repo.git'
```

I'm the **master** of the project, use Linux, `mina deploy` SSH to GitLab repository is fine and everything went smoothly.

But my colleague is **owner** of the project (higher privilege), use MacOS X, when he `mina deploy` turns out to be problem of SSH connecting to above Gitlab repository:

```     
-----> Using RVM environment 'ruby-2.3.3@default'        
       Using /home/user/.rvm/gems/ruby-2.3.3 
-----> Creating a temporary build path        
-----> Fetching new git commits        
       ! ERROR:        GitLab: The project you were looking for could not be found.
Deploy f       fatal: Could not read from remote repository.
       
       Please make sure you have the correct access rights
       and the repository exists.
 !     ERROR: Deploy failed.
-----> Cleaning up build        
       Unlinking current 
       OK 

 !     Command failed.
       Failed with status 1 (19)
```

What happened?

**Comment by adam12** [comment]
Are you using deploy keys? If you're not, it's possible that your machine is forwarding keys, and his isn't.
