### ISSUE TITLE
Mina 1.0.6, on windows, fork() function is unimplemented on this machine

### ISSUE THREAD

**Issue by insub** [mina-deploy/mina#534]
On my windows, setup mina version = 1.0.6
when i run "mina deploy", still have error:
**fork() function is unimplemented on this machine**

ruby 2.3
rails 5.0.0.1

More info:
mina deploy -t :
** Invoke deploy (first_time)
** Execute deploy
** Invoke environment (first_time)
** Execute environment
** Invoke git:clone (first_time)
** Execute git:clone
** Invoke deploy:link_shared_paths (first_time)
** Execute deploy:link_shared_paths
** Invoke bundle:install (first_time)
** Execute bundle:install
** Invoke rails:db_migrate (first_time)
** Execute rails:db_migrate
** Invoke rails:assets_precompile (first_time)
** Execute rails:assets_precompile
** Invoke deploy:cleanup (first_time)
** Execute deploy:cleanup
mina aborted!
NotImplementedError: fork() function is unimplemented on this machine
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/open4-1.3.4/lib/open4.rb:62:in `fork'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/open4-1.3.4/lib/open4.rb:62:in `do_popen'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/open4-1.3.4/lib/open4.rb:34:in `popen4'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/mina-1.0.6/lib/mina/runner/pretty.rb:15:in `run'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/mina-1.0.6/lib/mina/runner.rb:14:in `run'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/mina-1.0.6/lib/mina/commands.rb:49:in `block in run'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/mina-1.0.6/lib/mina/helpers/internal.rb:39:in `report_time'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/mina-1.0.6/lib/mina/commands.rb:48:in `run'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/mina-1.0.6/lib/mina/dsl.rb:30:in `run'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/mina-1.0.6/lib/mina/dsl.rb:49:in `deploy'
D:/Sites/rongzhi/config/deploy.rb:48:in `block in <top (required)>'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_ch
n'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
D:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in t
_level'

**Comment by RedNoo** [comment]
do you have any solution for this problem?

**Comment by skyway777** [comment]
You can try to set in config/deploy.rb
set :execution_mode, :exec if RbConfig::CONFIG['host_os'] =~ /mswin|mingw/

**Comment by lovro-bikic** [comment]
This should be fixed with https://github.com/mina-deploy/mina/pull/686, which will be released in 1.3.0. We used to use the [open4](https://github.com/ahoward/open4) gem which calls `fork`, but it has since been replaced with the Windows-compatible [open3](https://github.com/ruby/open3).
