### ISSUE TITLE
why mina setup  new a file use makdir -p 

### ISSUE THREAD

**Issue by zhangmingju** [mina-deploy/mina#538]
> fetch(:shared_files, []).each do |linked_path|
     command %{mkdir -p "#{File.dirname(linked_path)}"}
 end

**Comment by adam12** [comment]
This is a sanity check to ensure that the destination folder of the symbolic link actually exists before attempting to create it.

**Comment by d4be4st** [comment]
because the deploy would fail if all shared folders are not created, and to ensure that we use `-p`
