### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [mina-deploy/mina#541]
Again...

**Comment by ayghor** [comment]
plz dont let mina die =o(

**Comment by myserg** [comment]
Just maintain it. But don't make another capistrano.

**Comment by we-CONECT-Joe** [comment]
i would agree... a lot of dependenies like mina-nginx and mina-hooks are not even beeing maintained anymore... so unless you want to start puzzleling... its been dead a long time now.

**Comment by d4be4st** [comment]
I finally found the time to work on mina again!
In our company we use `mina` in all our projects so I wont let it die.

I have made some guarantees that every week issues and PR will be answered
