### ISSUE TITLE
How Mina work?

### ISSUE THREAD

**Issue by 1c7** [mina-deploy/mina#546]
Hi, 
Can anyone explain how Mina work generally? (on big picture level? and maybe dive into some detail?)
* how mina use ssh? why there are forward_agent? and permission problem?( fail to mkdir ) 
* what file is the "key" file? contain most logic or something
* just overall concept

it's easier for other people to continue to maintain this project.

* who created this? 
* why created this? (during working for ___ company. because ____, so ____ ?)
* when?
* is creator still actively working on this?
* please put all these into Readme
* not everyone want go though commit history and do research to find out all these question

Thank you very much!

**Comment by kuboon** [comment]
> how mina use ssh?

mina uses local ssh command.
see https://github.com/mina-deploy/mina/blob/master/lib/mina/backend/remote.rb

> who created this?
see https://github.com/mina-deploy/mina#credits

**Comment by kuboon** [comment]
> not everyone want go though commit history and do research to find out all these question

You can do research to save others ;)

**Comment by 1c7** [comment]
@kuboon Thank you very much!

**Comment by d4be4st** [comment]
Can you take a look at https://github.com/mina-deploy/mina/blob/master/docs/how_mina_works.md and see if that is what you needed?

**Comment by 1c7** [comment]
@d4be4st Thanks！
