### ISSUE TITLE
Why mina default link shared directory to public/assets?

### ISSUE THREAD

**Issue by Feuda** [mina-deploy/mina#550]
How to disable it?

`set :shared_dirs, fetch(:shared_dirs, []).push('log', 'tmp/pids', 'tmp/sockets', 'public/avatar')
`

I did not set 'public/assets' in deploy file

**Comment by adam12** [comment]
The `shared_dirs` variable likely has `public/assets` in it from one of your requires at the top.

You could try removing it from the array:

```
set :shared_dirs, fetch(:shared_dirs, []).push('log', 'tmp/pids', 'tmp/sockets', 'public/avatar') - ['public/assets']
```

Or set the array without fetching it first, but this might have other consequences:

```
set :shared_dirs, ['log', 'tmp/pids', 'tmp/sockets', 'public/avatar']
```

**Comment by d4be4st** [comment]
you can run `mina -d` to see all folders that are in `shared_dirs` 
and you can then assign your own values as @adam12 wrote

Mina needs `public/assets` because we do not want to do precomplie on every deploy so mina can be fast.
