### ISSUE TITLE
[Feature Request] Log of deploys to server (date, branch, commit, etc)

### ISSUE THREAD

**Issue by brunzino** [mina-deploy/mina#553]
Please don't judge our process, but I have encountered several times a need to remember which branch is on our staging server or which version, commit is on our production server. This could be solved by having a "deploy log" which gets added to after each deploy. I recognize Mina is version control agnostic, so this would probably be added of the mina/git module. 

I'd be open to trying my hand at building this out, but I wanted to check with the community to see if anyone else has this need, get the blessing of the team before contributing, and ask for any feedback on the feature or implementation.

Thanks!

**Comment by zmckenzie** [comment]
I haven't used the newest version of mina yet, however on the old version you can look in the scm folder and there's a file called FETCH_HEAD that should have your latest commit hash along with the branch and repo.

**Comment by d4be4st** [comment]
there is a file `current/.mina_git_revision` which stores the current commit hash.
Is that what you are looking for?

But what you are suggestion is to have a `deploy.log` in `deploy_to` path that has all deploys logged?

**Comment by lovro-bikic** [comment]
Hey, thanks for the idea! Since there were other queries about this, I've opened a main issue (#679) where we'll define this feature in full.
