### ISSUE TITLE
py-mina

### ISSUE THREAD

**Issue by cidevant** [mina-deploy/mina#564]
Hello,

recently our company decided to use python as primary devel language. So I had to write (rewrite) our deploy scripts from 'mina' to something else. There are many automation tools (ansible, salt, etc),  but we all agreed, that we want "pure" python.

I simulated `mina` behaviour in python and created project [py-mina](https://github.com/py-mina-deploy/py-mina). 

I want to ask you, if you can add link to my project in your docs somewhere. Just mention about python version/fork, nothing more.

Best regards,

Cidevant Von Goethe

**Comment by cidevant** [comment]
Also I ask a permission to use some parts of your docs in my py-mina docs, because we are so similar)

**Comment by d4be4st** [comment]
Hi!

Yes I do not have any objections to this.
In the next couple of weeks I intend to upgrade the documentation significantly so keep an eye on this.

I will add the link to somewhere in the docs yes :)
