### ISSUE TITLE
Mina setup doesn't symlink the current folder

### ISSUE THREAD

**Issue by jmuheim** [mina-deploy/mina#571]
After `mina deploy`, the "current" folder is effectively a folder, and not a symlink:

```
www-data@zugangfueralle01:~/reto.access4all.ch/rails $ ls -lsah
total 28K
4.0K drwxr-xr-x 7 www-data www-data 4.0K Sep 29 13:14 .
4.0K drwxr-xr-x 3 www-data www-data 4.0K Sep 29 12:14 ..
4.0K drwxr-xr-x 4 www-data www-data 4.0K Sep 29 13:14 current
4.0K drwxrwxr-x 3 www-data www-data 4.0K Sep 29 13:14 releases
4.0K drwxrwxr-x 7 www-data www-data 4.0K Sep 29 13:11 scm
4.0K drwxrwxr-x 7 www-data www-data 4.0K Sep 29 13:01 shared
4.0K drwxrwxr-x 2 www-data www-data 4.0K Sep 29 13:14 tmp
```

But it should look like this:

```
current -> /home/www-data/audit.access4all.ch/rails/releases/1
```

I always have to fix this manually like so: `rm -rf current`, then `ln -s releases/1/ current`.

Luckily, when doing another `mina deploy`, it correctly updates the symlink.

**Comment by d4be4st** [comment]
mina setup does not symlink folders, it only creates the needed folder structure (cant symlink something that does not exist yet)

Also it does not create the `current` folder.

Run `mina setup --simulate` and `current` folder shouldn't be there.

**Comment by jmuheim** [comment]
> Also it does not create the current folder.

In my case the `current` folder clearly was there after `mina setup`.

I will take a look at this again.
