### ISSUE TITLE
Task :environment not valid any longer

### ISSUE THREAD

**Issue by kamk** [mina-deploy/mina#583]
I'm using rbenv and I've noticed it stopped working after an update to some version. I figured out that in deploy.rb it should be:
```ruby
task :remote_environment do
   invoke :'rbenv:load'
end
```
It guess it should be corrected in vanilla config file generated by `mina init`.

However, when I try to run `mina -s rake[--tasks]` I see the environment, that is rbenv initialization is done **after** command invocation so I'm getting "Could not find rake-12.1.0 in any of the sources" because it's not using rbenv's version of ruby.

**Comment by d4be4st** [comment]
https://github.com/mina-deploy/mina/pull/577/files fixes this, i just forgot to push a new release. sorry about that!

1.2.2 has this fix now :)

**Comment by Nekromancer** [comment]
I think documentation should reflect :environment removal
