### ISSUE TITLE
Asset precompilation skip issue

### ISSUE THREAD

**Issue by sosedoff** [mina-deploy/mina#60]
I encountered the issue with asset precompilation. 

Our app has config option `config.assets.compile = false`, which triggers exception when required asset (in our case `admin.css`) is not precompiled. Adding the asset into the precompilation list should solve it: `config.assets.precompile += ['admin.css']`

Here is the issue. Mina skips asset precompilation and thus causes application to fail after next successful deploy. I fixed it by removing the asset folder and ran the deploy again. 

Any tips on this?

**Comment by tonytonyjan** [comment]
+1

**Comment by d4be4st** [comment]
mina only check diff of app/assets and vendor/asses for changes. Does not check any other as you can create your own intialize files which could change assets configs.

Please use `mina deploy force_assets=1`

**Comment by thelucid** [comment]
@d4be4st But what about engine assets?

**Comment by kazimzaidi** [comment]
Any way to have that option (force_aseets=1) inside the config/deploy.rb ?

**Comment by creativetags** [comment]
Inside config/deploy.rb

`set :force_asset_precompile, true`

Seems to work
