### ISSUE TITLE
Can't invoke rake task from script

### ISSUE THREAD

**Issue by rhombl4** [mina-deploy/mina#615]
When i run my rake task directly `mina staging rake[backup:db]` it's working fine, but when i try to do this thru deploy-script by `mina staging backup_db` i got error `Don't know how to build task 'rake[backup:db]'`

```
desc 'Backup database.'
task backup_db: :remote_environment do
  invoke :'rake[backup:db]'
end
```

**Comment by AnubixXx** [comment]
I have the same problem. 

Actually I can run from terminal: mina rake[sitemap:create]
If i add it to deploy.rb like: invoke :'rake[sitemap:create]', it doesnt work.
I also tried co create task like u, still the same problem, rake[sitemap:create] command not found.

**Comment by jonnynux** [comment]
Similar problem here, if I invoke two, or more, consecutive command, only the first is called. If I have other command, but not invokes, the command are executed.

**Comment by lovro-bikic** [comment]
When using `rake` or `rails` commands from deploy scripts, the task that you want to execute should be passed as an argument, like this:
```ruby
task :backup_db do
  invoke :rake, 'backup:db'
end
```
or, with Rails:
```ruby
task :backup_db do
  invoke :rails, 'backup:db'
end
```
