### ISSUE TITLE
Is it possible to run mina on the same server?

### ISSUE THREAD

**Issue by crysfel** [mina-deploy/mina#618]
I'd like to use mina to automate my deployment, however.... I'm wondering if is possible to run mina from the actual server.

What I want to do is to ssh into my server, then run mina from there and execute all the deployment from there.

Is this possible?

**Comment by anduonghien** [comment]
Same here :)

**Comment by coderhs** [comment]
ya, you just set the SSH to your own machine. place your public IP or Local IP. or 127.0.0.1. Don't forget to instal ssh server first.

**Comment by lovro-bikic** [comment]
Yes, this is possible, I'll just expand a bit on @coderhs's answer.

You need to install and run an ssh server on your machine (the steps depend on your OS), and add your public key to authorized keys:
```
$ cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
```

Then set the domain to localhost in your `config/deploy.rb`:
```ruby
# config/deploy.rb
set :domain, 'localhost' # or 127.0.0.1
```
and you're good to go!

Hope this helps.
