### ISSUE TITLE
Git SHA information on deploy or rollback

### ISSUE THREAD

**Issue by mcnelson** [mina-deploy/mina#626]
Hi. I was just curious if Mina establishes a means of seeing the live Git SHA after deployment or rollback? Would be very helpful to know.

Edit- To clarify, I am looking for it on the server, such as Capistrano's REVISION file.

**Comment by sunny** [comment]
There is a file `current/.mina_git_revision` which stores the current commit hash. Is this what you were looking for?

**Comment by mcnelson** [comment]
Exactly! Thanks.
