### ISSUE TITLE
mina puma:start won't start

### ISSUE THREAD

**Issue by wenesk** [mina-deploy/mina#632]
hello,

i'm running some issue on my 2nd project, somehow ```mina puma:start``` won't start the puma server on my servers. This is the result:

```
-----> Set domain to my server
-----> Using RVM environment 'ruby-2.3.1@default'
Using /home/user/.rvm/gems/ruby-2.3.1
-----> Start myapp's Puma server
Puma starting in single mode...
* Version 3.12.0 (ruby 2.3.1-p112), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: production
* Daemonizing...
Connection to [IP-ADDRESS] closed.
   Elapsed time: 2.56 seconds
```
looks promising, but still no puma working on the server. I usually use ```ps aux | grep puma``` to check the service.

But when I peek on the code (using ```mina puma:start -S```) and copy paste the code manually on my server, it run normally.

the code looks like this:

```
cd /home/user/myapp/current && RAILS_ENV="production" bundle exec puma -q -d -e production -b 'unix:///home/user/myapp/shared/tmp/sockets/puma.sock'  -S /home/user/myapp/shared/tmp/sockets/puma.state --pidfile /home/user/myapp/shared/tmp/pids/puma.pid --control 'unix:///home/user/myapp/shared/tmp/sockets/pumactl.sock'
```

but when i use ```mina puma:stop / restart``` from laptop (local), it also stop/restart the puma server on remote server. Just the start command is not working.

My first project (using mina+puma, ubuntu 16.04 & rails 5) running normally without any issue. But for 2nd project, I'm using ubuntu 18.04 & rails 5. 

I suspect the ubuntu's user to deploy the app maybe lack some permission maybe? because the server wasn't manage by me and I just given the username & password to access the server.

Any thoughts?

**Comment by krupa147** [comment]
facing the same issue.
Any updates on this?

**Comment by NBuhinicek** [comment]
Hey

it seems that you are using a 3rd party plugin ([mina-puma](https://github.com/sandelius/mina-puma)). Try looking there for further help with this.
