### ISSUE TITLE
Undefined local variable or method `git_source' for Gemfile

### ISSUE THREAD

**Issue by jasjeet30** [mina-deploy/mina#636]
`dev@appadmin-To-be-filled-by-O-E-M:/var/www/html/actioncableapi$ mina deploy`
`dev@192.168.1.111's password: `
`-----> Creating a temporary build path`
`-----> Fetching new git commits`
`       remote: Enumerating objects: 5, done.`
`remote: Counting objects: 100% (5/5), done.`
`remote: Compressing objects: 100% (1/1), done.`
`       remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0`
`Unpacking objects: 100% (3/3), done.   `
`       From https://github.com/jasjeet30/deploydemo`
`          3a66705..1937042  master     -> master`
`-----> Using git branch 'master'`
`       Cloning into '.'...`
`       done.`
`-----> Using this git commit`
`       Jasjeet Singh (1937042):`
`       > #git_source`
`-----> Symlinking shared paths`
`-----> Installing gem dependencies using Bundler`
`       Undefined local variable or method 'git_source' for Gemfile`
`               from /var/www/html/foobar/tmp/build-154952123832315/Gemfile:2`
` !     ERROR: Deploy failed.`
`-----> Cleaning up build`
`       Unlinking current`
`       OK`
`       Connection to 192.168.1.111 closed.`
``
`!     Run Error`

**Comment by NBuhinicek** [comment]
It's more of a project than mina error. 

The `git_source` was introduced in Bundler `1.6.0` so maybe you have an older version of Bundler.
