### ISSUE TITLE
Files differ

### ISSUE THREAD

**Issue by sloth456** [mina-deploy/mina#644]
Hi - I have been stuck with an issue for months that I still could not resolve, so any help is much appreciated.  

Everytime I run 'mina deploy' I come across this error

```
-----> Symlinking shared paths
       Files /var/www/test/current/db/migrate/20170423140256_create_jobs.rb and ./db/migrate/20170423140256_create_jobs.rb differ
```

Because of this the deployment fails and is rolled back.

I've tried downloading this file from my git repository and comparing it to my local version of the file using diff, cmp and also hexdump.

They all report absolutely no differences, so I can't understand why mina says there is a difference?

Happy to share any other details/answer questions that could help resolve this.

**Comment by NBuhinicek** [comment]
Hey

The `differ` message is just an indicator that something changed in the migrations since the old release and its a sign to run the migrations.

If you got issues after this messages, there is probably something wrong with the migration files. (probably an error occurring while migrating)

**Comment by lovro-bikic** [comment]
Closing for now. Will reopen if we get more info.
