### ISSUE TITLE
git clone "/app/scm"

### ISSUE THREAD

**Issue by VanyaNeytrino** [mina-deploy/mina#647]
Hello, I do not work deploy, because my can not put the path to the repository
**Using git branch 'master'**
$ "git clone "/app/scm" . --recursive --branch "master"
fatal: destination path '.' already exists and is not an empty directory.

**my repository**
set :repository, 'git@gitlab.com:VanyaNeytrino/app.git'

I've tried googling but no solution works for me.

**Comment by NBuhinicek** [comment]
Could you include your entire deploy.rb file? Thanks
