### ISSUE TITLE
How to ENV variables

### ISSUE THREAD

**Issue by misteral** [mina-deploy/mina#65]
is Gemfile line

gem 'spree', '1.2.0', :git => "https://#{ENV['GUSER']}:#{ENV['GPASS']}@bitbucket.org/constella/spree.git", :branch => "1-2-stable"

how i can set variable GUSER and GPASS ?

.bashrc on server -  not
.profile on server - not
queue! "export GUSER=memo"  in deploy - no

You have changed in the Gemfile:
       \* spree from `https://:@bitbucket.org/constella/spree.git (at 1-2-stable)` to `no specified source`

ERROR: Deploy failed.

**Comment by phanhaiquang** [comment]
I use Figaro

require 'yaml'

set :var_from_env, -> { YAML.load_file("./config/application.yml")["ENV_VAR"] }

**Comment by lulalala** [comment]
@rstacruz

May I ask is there a doc for `task :env do`? It does not append ENV setting in the command.

I used `set :bundle_prefix` to achieve this.

**Comment by AldanaQuintana** [comment]
@lulalala thanks, it worked for me!

I set bundle_prefix like this:

`set :bundle_prefix, 'env $(cat .env | xargs) bundle exec '`
