### ISSUE TITLE
[Question] Does mina have a plugin that record mina deploys?

### ISSUE THREAD

**Issue by coderhs** [mina-deploy/mina#653]
I wanted to ask if there is an existing code or plugin that allows one to log in to the server a deploy was done? We want to log our deploys just basic information such as when it happened.

**Comment by lovro-bikic** [comment]
At the moment there is no such plugin, but I agree that this would be useful to have. I've opened an issue (#679) which defines the feature and will track updates to it, so you can subscribe there.
