### ISSUE TITLE
Getting the following warnings when using bundler 2.1.2

### ISSUE THREAD

**Issue by thelucid** [mina-deploy/mina#657]
```
[DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set deployment 'true'`, and stop using this flag
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/bundle'`, and stop using this flag
[DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'development test'`, and stop using this flag
```

**Comment by masterkain** [comment]
I'm trying to adjust to the changes upgrading from 1.x to 2.1.x and here's some findings:

previous `deployment` flag:

```
bundle install --deployment --without development test --jobs 5 --retry 3
```

current:

```
bundle config set deployment 'true'
bundle config set without 'development test'
bundle install --jobs 5 --retry 3
```

the problem I see with this is that if this code runs in a `ruby:2.6-alpine` docker image (as part of a build step in a CI):

- with the current version `BUNDLE_PATH` env variable will take precedence over the `vendor/bundle` one that is supposed to be set by the `deployment` flag/config, and the ruby image will have that set

- with the previous version I had no issue

overriding `BUNDLE_PATH` manually in the image with the full path will make things work again, but it's not something I like to do.

I also tried with `bundle config set --local deployment 'true'` but I still have the same issue, bundle will install in a `BUNDLE_PATH` if set

**Comment by Haelle** [comment]
same warnings here with Bundler 2.1.4

And `bundle:clean` fails with : 
```
$ /usr/local/rbenv/shims/bundle clean --without development test --path "vendor/bundle" --deployment
       Unknown switches "--without", "--path", "--deployment"
 !     ERROR: Deploy failed.
```

**Comment by thelucid** [comment]
Any further info on this?

**Comment by thelucid** [comment]
For anyone arriving here, I am using the following solution:

First I remove the default bundler options.

```ruby
set :bundle_options, -> { '' }
```

Then I add the following to my `setup` task.

```ruby
command "#{fetch(:bundle_bin)} config set deployment 'true'"
command "#{fetch(:bundle_bin)} config set path '#{fetch(:bundle_path)}'"
command "#{fetch(:bundle_bin)} config set without '#{fetch(:bundle_withouts)}'"
```

This solves the depreciation warnings and sets the bundle config globally. I would be happy to write a patch for this if it is something that will get merged.

**Comment by Haelle** [comment]
This would break for anyone using Bundler 1.

And I'm not sure Mina team wants to handle a code with an `if bundler_1? do xxx esle do yyy`

**Comment by thelucid** [comment]
@Haelle Surely compatibility with the latest stable Bundler would be preferable, as upgrades are recommended. Mina could recommend a newer and therefore more stable version of Bundler. Currently Mina is unusable with the latest production Bundler.

**Comment by windy** [comment]
+1

**Comment by ibrahimyolbir** [comment]
Hi @thelucid  can you explain that more detailed. 
where is this set :bundle_options, -> { '' } options?
and to where i will add above commands. i am using gitlab runner and fastline for the app distribution. so i have gitlab-ci.yml file here a script like    
 - bundle install --path ./tmp-fastlane-ci-bundle

**Comment by risen** [comment]
@thelucid said:
> For anyone arriving here, I am using the following solution:
>
> ```ruby
> command "#{fetch(:bundle_bin)} config set deployment 'true'"
> command "#{fetch(:bundle_bin)} config set path '#{fetch(:bundle_path)}'"
> command "#{fetch(:bundle_bin)} config set without '#{fetch(:bundle_withouts)}'"
> ```
> 
> This solves the depreciation warnings and sets the bundle config globally. I would be happy to write a patch for this if it is something that will get merged.

Doesn't it make more sense to use:
```ruby
command "#{fetch(:bundle_bin)} config set --local deployment 'true'"
command "#{fetch(:bundle_bin)} config set --local path '#{fetch(:bundle_path)}'"
command "#{fetch(:bundle_bin)} config set --local without '#{fetch(:bundle_withouts)}'"
```
… on every deploy? For instance, I can imagine the `without` changing between releases.
