### ISSUE TITLE
No password was specified in environment variable CODA_PRIVKEY_PASS

### ISSUE THREAD

**Issue by subbame** [mina-deploy/mina#670]
As mentioned at [https://docs.minaprotocol.com/en/using-mina/connecting#ubuntu-1804--debian-9-1](https://docs.minaprotocol.com/en/using-mina/connecting#ubuntu-1804--debian-9-1) I have created a file called `~/.mina-env` with

```
CODA_PRIVKEY_PASS="private key password"
EXTRA_FLAGS=" --file-log-level Debug"
```

but I am still getting `FATAL ERROR Mina Daemon encountered a configuration error loading block producer keypair. No password was specified in environment variable CODA_PRIVKEY_PASS` while running

`mina daemon --block-producer-key ~/keys/my-wallet --generate-genesis-proof true --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt`

**Comment by airled** [comment]
Wrong project. I think you need [this one](https://github.com/MinaProtocol/mina).

**Comment by lovro-bikic** [comment]
Closing as this is the wrong project.
