### ISSUE TITLE
Mina Resurrection

### ISSUE THREAD

**Issue by lovro-bikic** [mina-deploy/mina#676]
Hi everyone.

You might have noticed the radio silence surrounding Mina in the last few years. Other obligations took precedence and Mina, as a result, suffered. We apologize for that to everyone who depended on it, the popularity of this project (more than a million downloads on RubyGems and a hundred other published Mina-related gems!) deserves better governance.

Mina is currently in the process of a revival. I will now outline a plan for releasing new features, fixing issues and responding to the community.

We have already released [v1.2.4](https://rubygems.org/gems/mina/versions/1.2.4) yesterday with bugfixes merged to master but never before released.

Issues and PRs have been looked through to get an idea of what’s important, and some have been answered. We have set two version milestones, 1.3.0 and 2.0.0, during which we aim to release new features. Some of the important features we’ll work on are:
- Windows support (there are some issues like https://github.com/mina-deploy/mina/issues/675 and https://github.com/mina-deploy/mina/issues/660), we’re aiming for 2.0.0
- plugin for version manager tasks which will add support for `asdf`, `nodenv` and many others (see https://github.com/mina-deploy/mina/issues/674 for more details), to be released in 1.3.0

We will respond to all issues and PRs and try to find a satisfying solution to each.

We’re also aware that documentation isn’t exemplary. This problem will be tackled too in the following weeks by updating guides and providing information on Mina’s architecture so that people can understand it and contribute to it more easily.

To ensure that Mina doesn’t die again, we will internally set up a schedule so that maintainers respond to issues and PRs in reasonable time. We’ll also enable Github Discussions so that you can have better communication with the maintainers and the rest of the community.

By taking all these steps, I sincerely hope this is the last time we’ll have to post this kind of an update. Thank you to everyone for their interest in Mina, feedback and contributions are more than welcome!

**Comment by deanpcmad** [comment]
Seeing as this has now been closed, does this mean the project is still going?
If not, I'd be happy to take over the repo and gem as I still use Mina for all my projects.

**Comment by lovro-bikic** [comment]
The project is still going, I closed the issue because it's been open for almost a year.
