### ISSUE TITLE
Git commit message with non ASCII character raises error

### ISSUE THREAD

**Issue by fuadsaud** [mina-deploy/mina#68]
Running deploy with the last git commit message containing a non ASCII character throws:

_invalid byte sequence in US-ASCII_

**Comment by omer-clustox** [comment]
any update on this issue ? My name and commit message has no special character. Still I am getting this message.
<img width="761" alt="screenshot 2016-10-27 15 31 24" src="https://cloud.githubusercontent.com/assets/4695218/19764040/6f6b78fa-9c5a-11e6-89b6-34635cf7715f.png">

**Comment by omer-clustox** [comment]
Got it resolved. Issue was due to missing local on my local pc. I run following on my terminal 

> export LC_ALL="en_US.UTF-8"
then check 

> locale

mina deploy works fine now
