### ISSUE TITLE
mina 1.2.4: Allow multiple deployments with different `RAILS_ENV`

### ISSUE THREAD

**Issue by abhinavc** [mina-deploy/mina#713]
I am looking to deploy two instances of a Rails app on a VPS - one for production and one for sandbox (or  staging / testing).

But it seems to me that `mina` wouldn't allow it. 

In task `rails:db_migrate`,  `rails_env` is hard-coded to `production` with no means to override it. And this `rails_env` then percolates down to `bundle_prefix` and thence to `rake` and `rails` etc. 

Could a way be provided therefore to `set :rails_env` to something other than the default `production`? 

![Screenshot 2022-09-20 at 8 26 16 PM](https://user-images.githubusercontent.com/106936/191292859-d1610422-f3be-4f20-ad80-c6574a8bd03a.png)

**Comment by lovro-bikic** [comment]
You can override variables in your `deploy.rb` script.

If you set:
```ruby
# config/deploy.rb
require 'mina/rails'

set :rails_env, 'staging'
```
it will set the `rails_env` variable to `staging` (or rather, override the the value `staging` will override the value `production`).

Regarding deploying to multiple environments, see [this](https://github.com/mina-deploy/mina/blob/master/docs/cookbook.md#multi-environment-deploy) code sample, and let me know if it helps.

**Comment by abhinavc** [comment]
Thanks @lovro-bikic
