### ISSUE TITLE
Ugh... not able to fetch new commits

### ISSUE THREAD

**Issue by staycreativedesign** [mina-deploy/mina#720]
-----> Fetching new git commits                                                                                                      
       Warning: the RSA host key for 'github.com' differs from the key for the IP address '140.82.114.4'                               
       Offending key for IP in /home/deployer/.ssh/known_hosts:6                                                                        
       Matching host key in /home/deployer/.ssh/known_hosts:8

**Comment by lovro-bikic** [comment]
This is a result of GitHub changing its SSH host key (https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key).

You can resolve this by SSH-ing to the server (you can do it via Mina with the command `mina ssh`) and replacing the host key in the `known_hosts` file, which is explained in [this part of the blog post](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/#what-you-can-do).
