### ISSUE TITLE
mina init fails with NoMethodError: undefined method `exists?' for File:Class

### ISSUE THREAD

**Issue by snex** [mina-deploy/mina#721]
As of ruby 3.2.0, File.exists? has been renamed to File.exist?

**Comment by jlkwarteng** [comment]
Using gem 'mina', github: 'mina-deploy/mina' did not seem to work for me @gior

**Comment by lovro-bikic** [comment]
This has been resolved in [v1.2.5](https://github.com/mina-deploy/mina/releases/tag/v1.2.5).
