### ISSUE TITLE
Deploy to multiple boxes simultaneously

### ISSUE THREAD

**Issue by pointlessone** [mina-deploy/mina#8]
If I'm not mistaken it's possible to deploy only to single box. I.e. if I have a bunch of identical boxes I have to deploy to each of them explicitly specifying to which box I deploy. Something like this:

~~~
mina deploy to=prodbox1 && mina deploy to=prodbox2 && mina deploy to=prodbox3
~~~

Is parallel deployment planned anytime soon?

**Comment by livecube** [comment]
Thanks @phlipper - you saved my life.

+1 for true parallel deployments!

**Comment by iMoses** [comment]
Almost three years and not a step forward, let alone a decent response?

**Comment by zacksiri** [comment]
capistrano 3 is actually really good i've switched to using it.

**Comment by josericardo** [comment]
Based on the first scenario described by @cheba, it could be as simple as:

cat list_of_servers.txt | parallel mina deploy to={}

Any drawbacks on running multiple mina processes?

**Comment by cheba** [comment]
@josericardo It's sort of working but not quite. Specifically, you may not want to perform complete deploy on each box. You want to run migrations only once (say, if you have many app servers and one db server). You may want to upload your assets to CDN only once. There are legitimate reasons for having native support for multiple destinations.

**Comment by nickckaye** [comment]
https://www.npmjs.com/package/mina

**Comment by brendonrapp** [comment]
Just as I was digging into Mina for our new deployment setup, I run into this and get stopped dead in my tracks.

Deploying to multiple application servers isn't just a matter of "run the task on all boxes". There's also coordination, eg. if the deploy on one box fails, recognize that and roll back the deployment on all of them, lest you end up with different versions running at the same time. Hence just looping through a domain list and firing off the deploy task on each of them is no solution.

Very disappointing, complete deal-breaker.

**Comment by nickckaye** [comment]
Hey @brendonrapp yes, I agree. I love the concept of Mina, but the bottom line is that Capistrano is a vastly more mature product. It represents many years of real-world experience deploying complex production environments. The Mina project is thousands of developer hours short of it.

**Comment by d4be4st** [comment]
We need help on this. As we do not use multiple servers in our company there really is not a high prioriy.
But we would appreciate PRs.
Thx

**Comment by akbarbin** [comment]
I just want to share how to use multiple deploying server or environment with mina. Mina have a 3rd party to deploy in multiple stages. You can use mina-multistages this the url https://github.com/endoze/mina-multistage. It's really powerful to manage your deploy env.
I hope this help you all. Thanks

**Comment by gknapp** [comment]
I read about using Mina in conjunction with Ansible for multi host deployments.

+1 to see this added natively to mina

**Comment by grsahil20** [comment]
+ 1 BUMP

**Comment by rodolfospalenza** [comment]
+1

**Comment by Mothirajha** [comment]
any solution for parallel deployment using mina ??

**Comment by at-binhcq** [comment]
Still waiting for native sollution.
While waiting, I'm still using @phlipper 's solution.

**Comment by d4be4st** [comment]
Mina doesn't do multiple boxes and probably never, because it is meant to be used as one quick script on one remote host. 
I am sorry about this.
There is a great tool [capistrano] that does this job well.

**Comment by Juanmcuello** [comment]
I created a very simple gem called [mina-multi_server](https://github.com/Juanmcuello/mina-multi_server) that adds support for multiple servers. It runs tasks sequentially, but probably it is not an issue if you don't have a lot of servers.

All comments are appreciated.

**Comment by hugopl** [comment]
This is a blocker to anyone using e.g. sidekiq server in another dedicated box.

**Comment by iBcker** [comment]
mina 2.x

set :domains, %w[host1 host2 host3]
desc "Deploy to all servers"
task :deploy_all do
    fetch(:domains).each do |domain|
      set :domain, domain
      invoke :deploy
    end
end

**Comment by msshahanshah** [comment]
+1

**Comment by volkov-sergey** [comment]
We built mina-multideploy - useful tool for parallel deploying on multiple servers https://github.com/codica2/mina-multideploy

**Comment by emptyflask** [comment]
Something like this could work for handling roles. Again, not parallel (yet).

```
task :staging do
  set :domains, 'staging-1.app.com' => [:db], 'staging-2.app.com' => []
end

task :deploy do
  # uncomment this line to make sure you pushed your local branch to the remote origin
  invoke :'git:ensure_pushed'

  fetch(:domains).each do |domain, roles|
    set :domain, domain

    deploy do
      # Put things that will set up an empty directory into a fully set-up
      # instance of your project.
      invoke :'git:clone'
      invoke :'deploy:link_shared_paths'
      invoke :'bundle:install'
      invoke :'rails:db_migrate' if roles.include?(:db)
      invoke :'rails:assets_precompile'
      invoke :'deploy:cleanup'

      on :launch do
        in_path(fetch(:current_path)) do
          command %(mkdir -p tmp/)
          command %(touch tmp/restart.txt)
          command %(direnv allow)
        end
      end
    end
  end
end
```
