### ISSUE TITLE
Early Deletion of .git repo

### ISSUE THREAD

**Issue by MafcoCinco** [mina-deploy/mina#80]
I apologize if this is user error, but I am unable to get `mina` to deploy gems as the shell script generated by `git.rb` deletes the `.git` directory before executing the user defined portions of the `deploy` task.  This is a problem as our `.gemspec` files use `git ls-files` to fill in the file list for the Gemspec DSL.

When `rake build` or `gem build foo.gemspec` is invoked in the `deploy` task, an error is thrown as the `.git` directory no longer exists.  For rails, deleting the `.git` directory is probably not a big deal, but it makes things very difficult when deploying stand alone gems that are built on the remote server and pushed to a local instance of Gem-in-a-box.

Would anyone be opposed to moving the `rm -rf .git` command out of `git.rb` and into `data/deploy.sh.erb`.  A good place might be right after the bootstrap section.

Again, if there is something I'm missing here and anyone can suggest a way to accomplish what I want (i.e. building gems on the remote server while still having `git ls-files` populating the file list in the `.gemspec`) I will happily use your suggestion.  However, from what I have attempted so far this seems to be an issue in `mina` related to the fact that the `.git` directory is deleted prior to executing the user defined portion of the `deploy` task.

Thanks.

**Comment by d4be4st** [comment]
this might be a good mina-gem that you can include which would overwrite the deauft git tasks.
We want this to stay in mina as is
