### ISSUE TITLE
Help wanted: Windows mingw32 shell (git bash) - CRLF

### ISSUE THREAD

**Issue by reterius** [mina-deploy/mina#83]
First things first - thanks for great tool :+1: 

I am using Windows now (yeah...) and trying to deploy with Mina.

I found that generated bash script on Windows Git Bash (mingw32 standard shell) has CRLF line endings, but linux use LF, so there are errors like "Unexpected EOF".

I write this generated script to file, convert line endings to LF and use it manually - everything works fine.

Is this a Mina feature or a mingw32 bug or misconfiguration? :)

**Comment by kim3er** [comment]
Would it help progress this issue, if I put @insub's fix into a pull request?

**Comment by dynasource** [comment]
@coredevelopers: any reason why this isnt picked up? Solution by insub works. Why not do minor patches to support the windows community?

**Comment by dima-stefantsov** [comment]
It works indeed. Thanks!

**Comment by d4be4st** [comment]
Can someome test github master if this works?
