### ISSUE TITLE
Rolling back to previous release

### ISSUE THREAD

**Issue by thelucid** [mina-deploy/mina#9]
I am currently using Vlad and Mina looks like a much cleaner alternative as Vlad isn't maintained much anymore.

I might be missing something obvious but is there a way to roll back to a previous release?

**Comment by jmuheim** [comment]
+1

**Comment by born4new** [comment]
+1, Thanks @tmandry !

**Comment by mcescalante** [comment]
+1 @tmandry nice task to take care of it for the time being!

**Comment by jerefrer** [comment]
For @d4be4st ... HURRAY \o/

**Comment by jmuheim** [comment]
:+1: :dancer:

**Comment by d4be4st** [comment]
Mina v0.3.3 released with rollback feature

**Comment by elfuego** [comment]
In https://github.com/mina-deploy/mina/issues/9#issuecomment-37499645 use for sort `sort -n` to make sure the release numbers are not sorted as strings but as numbers.

**Comment by dmersiowsky** [comment]
Improvement for https://github.com/mina-deploy/mina/issues/9#issuecomment-35467629, https://github.com/mina-deploy/mina/issues/9#issuecomment-37499645, also using https://github.com/mina-deploy/mina/issues/9#issuecomment-99877069:

First: Tank you for sharing, I'd have gone nuts without the existing examples. 
@elfuego @tmandry @mbahar 

New feature: This one checks if a release to possibly roll back to does even exist. 
If not, it does not execute the rollback. 

Since 

    mina deploy:rollback

does not do this, I'm afraid it's useless for me.



Code:

    desc "Rolls back the latest release"
    task :rollback => :environment do
        queue! %[echo "-----> Rolling back to previous release for instance: #{domain}"]
        queue %[echo "-----> Current release : "]
        queue %[ls "#{deploy_to}/releases" -Art | sort -n | tail -n 1]

        queue %[echo "-----> Release to roll back to :"]
        queue %[
            # ls command below must return two rows. first of the two contains the 2nd latest version.
            last=`ls "#{deploy_to}/releases" -Art | sort -n | tail -n 2 | sed -n '1p'` &&
            current=`ls "#{deploy_to}/releases" -Art | sort -n | tail -n 2 | sed -n '2p'` &&
            if [ ! -n "last" ] || [ ! -n "$current" ] || [ ! -d "#{deploy_to}/releases/$last" ];
            then
                echo "ERROR: No version to roll back to!";
                exit 1;
            fi
          ]
    
        queue %[ls "#{deploy_to}/releases" -Art | sort -n | sed -n '2p']

        # remove latest release folder (active release)
        queue! %[ls "#{deploy_to}/releases" -Art | sort -n | tail -n 1 | xargs -I active rm -rf #{deploy_to}/releases/active"]

        # delete existing sym link and create a new symlink pointing to the previous release
        queue %[echo "-----> Creating new symlink from the previous release: "]
        queue %[ls "#{deploy_to}/releases" -Art | sort | tail -n 1]
        queue! %[rm "#{deploy_to}/current"]
        queue! %[ls -Art "#{deploy_to}/releases" | sort | tail -n 1 | xargs -I active ln -s "#{deploy_to}/releases/active" "#{deploy_to}/current"]
    end
