### ISSUE TITLE
Do some tasks after deploy

### ISSUE THREAD

**Issue by musashimm** [mina-deploy/mina#98]
I want to do some tasks after deploy. So i put invoke as last entry in deploy section

    desc "Deploys the current version to the server."
    task :deploy => :environment do
      deploy do

      to :launch do
        queue 'touch tmp/restart.txt'
        invoke :qwerty
      end
    end
    end

    task :qwerty do
      puts "ls"
      system 'ls'
    end

But ls command is run before commands in the queue:

    ls
    Gemfile  Gemfile.lock  README.rdoc  Rakefile  app config  config.ru  db	doc  lib  log  public  script  test  tmp  vendor
    -----> Creating a temporary build path
    -----> Fetching new git commits
    -----> Using git branch 'master'

So how to check if deploy is finished or run command after deploy.

**Comment by d4be4st** [comment]
this can be done with :after_hooks in newer mina versions
