### ISSUE TITLE
Password prompt in mina doesn't work

### ISSUE THREAD

**Issue by seifsallam** [mina-deploy/mina#99]
Typing the password then hitting enter doesn't do anything. But when I hit another enter it checks the SSH password and returns `Permission denied, please try again.`

*********[ENTER] — doesn't work

*********[ENTER][ENTER] — permission denied

I haven't done anything in the project except for `mina init`, set user, domain, deploy_to, repo, then `mina setup` (which doesn't work)

So is there anything i'm missing here or there is a bug?

**Comment by udit7590** [comment]
Thanks a lot for the fix... But what was the actual problem?

**Comment by ChengwayLin** [comment]
@seifsallam thanks a lot !!

**Comment by lexalexander10** [comment]
Thanks for this! What exactly does this do?

**Comment by joshuasoehn** [comment]
Thanks a lot!

**Comment by Kalizo** [comment]
Thanks ! I fix it with @seifsallam solution

**Comment by yihyang** [comment]
Thanks! @seifsallam

**Comment by micfan** [comment]
@seifsallam It works under OSX 10.11.2. Thank you!

**Comment by onedal** [comment]
Thank you!

**Comment by flameA** [comment]
thank. it correct

**Comment by jichengyue** [comment]
thanks，it is good

**Comment by wiredin** [comment]
Just installed mina, why on earth does this bug exist? someone care to explain? terrible start for someone new to using this tool.  @rstacruz @fbarbier @awUsers  hello???

**Comment by mokolabs** [comment]
Agreed. Maybe `set :term_mode, nil` could be a default at this point?

**Comment by naveed-ahmad** [comment]
+1 for default. Faced same issue in 2017 -:)

**Comment by smlparry** [comment]
Im using Mina v1.0.6 and I had to use:
```
set :execution_mode, :system
```
https://github.com/mina-deploy/mina/blob/master/docs/faq.md#--mina-hangs-after-i-type-my-password-in

**Comment by jarvisjohnson** [comment]
thanks a bunch @smlparry - Mina was just hanging on `cloning into bare repository`.  This setting finally prompted for my github username and password.  Appears necessary for any private repos

**Comment by nukturnal** [comment]
looks like @smlparry's solution works in 2018 +1

**Comment by IrineuFilho** [comment]
@smlparry 's solution works in 2019 (version 1.2.3)
